const MEDICINES_DB = [
  // ===== ANALGESICS & ANTIPYRETICS =====
  { id: 1, name: "Crocin", genericName: "Paracetamol", category: "Analgesic/Antipyretic", forms: ["Tab", "Syp", "Drop", "Susp"], strengths: ["500mg", "650mg", "125mg/5ml", "250mg/5ml"] },
  { id: 2, name: "Dolo", genericName: "Paracetamol", category: "Analgesic/Antipyretic", forms: ["Tab", "Susp", "Drop"], strengths: ["650mg", "500mg", "250mg/5ml", "100mg/ml"] },
  { id: 3, name: "Calpol", genericName: "Paracetamol", category: "Analgesic/Antipyretic", forms: ["Tab", "Syp", "Susp"], strengths: ["500mg", "120mg/5ml", "250mg/5ml"] },
  { id: 4, name: "Combiflam", genericName: "Ibuprofen + Paracetamol", category: "Analgesic/Anti-inflammatory", forms: ["Tab", "Susp"], strengths: ["400mg+325mg", "100mg+162.5mg/5ml"] },
  { id: 5, name: "Brufen", genericName: "Ibuprofen", category: "Analgesic/Anti-inflammatory", forms: ["Tab", "Syp", "Gel"], strengths: ["200mg", "400mg", "600mg", "100mg/5ml"] },
  { id: 6, name: "Sumo", genericName: "Nimesulide + Paracetamol", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["100mg+325mg"] },
  { id: 7, name: "Voveran", genericName: "Diclofenac Sodium", category: "Analgesic/Anti-inflammatory", forms: ["Tab", "Gel", "Inj", "Spray"], strengths: ["50mg", "100mg", "1%", "75mg/3ml"] },
  { id: 8, name: "Voveran SR", genericName: "Diclofenac Sodium SR", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["75mg", "100mg"] },
  { id: 9, name: "Zerodol SP", genericName: "Aceclofenac + Paracetamol + Serratiopeptidase", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["100mg+325mg+15mg"] },
  { id: 10, name: "Zerodol P", genericName: "Aceclofenac + Paracetamol", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["100mg+325mg"] },
  { id: 11, name: "Hifenac P", genericName: "Aceclofenac + Paracetamol", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["100mg+325mg"] },
  { id: 12, name: "Flexon", genericName: "Ibuprofen + Paracetamol", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["400mg+325mg"] },
  { id: 13, name: "Meftal Spas", genericName: "Mefenamic Acid + Dicyclomine", category: "Analgesic/Antispasmodic", forms: ["Tab", "Susp"], strengths: ["250mg+10mg", "50mg+10mg/5ml"] },
  { id: 14, name: "Meftal Forte", genericName: "Mefenamic Acid + Paracetamol", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["500mg+325mg"] },
  { id: 15, name: "Saridon", genericName: "Propyphenazone + Paracetamol + Caffeine", category: "Analgesic", forms: ["Tab"], strengths: ["150mg+250mg+50mg"] },
  { id: 16, name: "Disprin", genericName: "Aspirin", category: "Analgesic/Antipyretic", forms: ["Tab"], strengths: ["350mg", "500mg"] },
  { id: 17, name: "Ultracet", genericName: "Tramadol + Paracetamol", category: "Analgesic (Opioid)", forms: ["Tab"], strengths: ["37.5mg+325mg"] },
  { id: 18, name: "Drotin DS", genericName: "Drotaverine", category: "Antispasmodic", forms: ["Tab", "Inj"], strengths: ["80mg", "40mg/2ml"] },
  { id: 19, name: "Drotin Plus", genericName: "Drotaverine + Paracetamol", category: "Antispasmodic/Analgesic", forms: ["Tab"], strengths: ["80mg+325mg"] },
  { id: 20, name: "Nicip Plus", genericName: "Nimesulide + Paracetamol", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["100mg+325mg"] },
  { id: 21, name: "Etoricoxib", genericName: "Etoricoxib", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["60mg", "90mg", "120mg"] },
  { id: 22, name: "Nucoxia", genericName: "Etoricoxib", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["60mg", "90mg", "120mg"] },
  { id: 23, name: "Pirox DT", genericName: "Piroxicam", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["10mg", "20mg"] },
  { id: 24, name: "Ketorol DT", genericName: "Ketorolac", category: "Analgesic/Anti-inflammatory", forms: ["Tab", "Inj"], strengths: ["10mg", "30mg/ml"] },
  { id: 25, name: "Naprosyn", genericName: "Naproxen", category: "Analgesic/Anti-inflammatory", forms: ["Tab"], strengths: ["250mg", "500mg"] },

  // ===== ANTIBIOTICS =====
  { id: 26, name: "Augmentin", genericName: "Amoxicillin + Clavulanic Acid", category: "Antibiotic", forms: ["Tab", "Syp", "Inj"], strengths: ["375mg", "625mg", "1g", "228.5mg/5ml", "457mg/5ml", "1.2g"] },
  { id: 27, name: "Moxikind CV", genericName: "Amoxicillin + Clavulanic Acid", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["375mg", "625mg", "228.5mg/5ml"] },
  { id: 28, name: "Azee", genericName: "Azithromycin", category: "Antibiotic", forms: ["Tab", "Syp", "Susp"], strengths: ["250mg", "500mg", "100mg/5ml", "200mg/5ml"] },
  { id: 29, name: "Azithral", genericName: "Azithromycin", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["250mg", "500mg", "100mg/5ml"] },
  { id: 30, name: "Zifi", genericName: "Cefixime", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["100mg", "200mg", "50mg/5ml", "100mg/5ml"] },
  { id: 31, name: "Zifi CV", genericName: "Cefixime + Clavulanic Acid", category: "Antibiotic", forms: ["Tab"], strengths: ["200mg+125mg"] },
  { id: 32, name: "Taxim O", genericName: "Cefixime", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["200mg", "50mg/5ml"] },
  { id: 33, name: "Ceftas", genericName: "Cefixime", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["200mg", "100mg/5ml"] },
  { id: 34, name: "Monocef", genericName: "Ceftriaxone", category: "Antibiotic", forms: ["Inj"], strengths: ["250mg", "500mg", "1g", "2g"] },
  { id: 35, name: "Supacef", genericName: "Cefuroxime", category: "Antibiotic", forms: ["Tab", "Inj"], strengths: ["250mg", "500mg", "750mg", "1.5g"] },
  { id: 36, name: "Ciplox", genericName: "Ciprofloxacin", category: "Antibiotic", forms: ["Tab", "Drop", "Inj"], strengths: ["250mg", "500mg", "0.3%", "200mg/100ml"] },
  { id: 37, name: "Cifran", genericName: "Ciprofloxacin", category: "Antibiotic", forms: ["Tab", "Inj"], strengths: ["250mg", "500mg"] },
  { id: 38, name: "Levoflox", genericName: "Levofloxacin", category: "Antibiotic", forms: ["Tab", "Inj"], strengths: ["250mg", "500mg", "750mg"] },
  { id: 39, name: "Levomac", genericName: "Levofloxacin", category: "Antibiotic", forms: ["Tab"], strengths: ["250mg", "500mg"] },
  { id: 40, name: "Oflox", genericName: "Ofloxacin", category: "Antibiotic", forms: ["Tab", "Drop"], strengths: ["200mg", "400mg", "0.3%"] },
  { id: 41, name: "O2", genericName: "Ofloxacin", category: "Antibiotic", forms: ["Tab"], strengths: ["200mg", "400mg"] },
  { id: 42, name: "Norflox TZ", genericName: "Norfloxacin + Tinidazole", category: "Antibiotic/Antiprotozoal", forms: ["Tab"], strengths: ["400mg+600mg"] },
  { id: 43, name: "Flagyl", genericName: "Metronidazole", category: "Antibiotic/Antiprotozoal", forms: ["Tab", "Syp", "Inj", "Gel"], strengths: ["200mg", "400mg", "200mg/5ml", "500mg/100ml", "1%"] },
  { id: 44, name: "Metrogyl", genericName: "Metronidazole", category: "Antibiotic/Antiprotozoal", forms: ["Tab", "Syp", "Inj", "Gel"], strengths: ["200mg", "400mg", "200mg/5ml"] },
  { id: 45, name: "Fasigyn", genericName: "Tinidazole", category: "Antiprotozoal", forms: ["Tab"], strengths: ["300mg", "500mg"] },
  { id: 46, name: "Doxycap", genericName: "Doxycycline", category: "Antibiotic", forms: ["Cap"], strengths: ["100mg"] },
  { id: 47, name: "Doxt SL", genericName: "Doxycycline", category: "Antibiotic", forms: ["Cap"], strengths: ["100mg"] },
  { id: 48, name: "Roxid", genericName: "Roxithromycin", category: "Antibiotic", forms: ["Tab"], strengths: ["150mg", "300mg"] },
  { id: 49, name: "Althrocin", genericName: "Erythromycin", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["250mg", "500mg", "125mg/5ml"] },
  { id: 50, name: "Clavam", genericName: "Amoxicillin + Clavulanic Acid", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["375mg", "625mg", "228.5mg/5ml"] },
  { id: 51, name: "Amoxyclav", genericName: "Amoxicillin + Clavulanic Acid", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["375mg", "625mg"] },
  { id: 52, name: "Novamox", genericName: "Amoxicillin", category: "Antibiotic", forms: ["Cap", "Syp"], strengths: ["250mg", "500mg", "125mg/5ml", "250mg/5ml"] },
  { id: 53, name: "Mox", genericName: "Amoxicillin", category: "Antibiotic", forms: ["Cap", "Syp"], strengths: ["250mg", "500mg"] },
  { id: 54, name: "Ampicillin", genericName: "Ampicillin", category: "Antibiotic", forms: ["Cap", "Inj"], strengths: ["250mg", "500mg"] },
  { id: 55, name: "Cepodem", genericName: "Cefpodoxime", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["100mg", "200mg", "50mg/5ml", "100mg/5ml"] },
  { id: 56, name: "Mahacef Plus", genericName: "Cefixime + Ofloxacin", category: "Antibiotic", forms: ["Tab"], strengths: ["200mg+200mg"] },
  { id: 57, name: "Clindamycin", genericName: "Clindamycin", category: "Antibiotic", forms: ["Cap", "Gel", "Lotion"], strengths: ["150mg", "300mg", "1%"] },
  { id: 58, name: "Dalacin C", genericName: "Clindamycin", category: "Antibiotic", forms: ["Cap", "Inj"], strengths: ["150mg", "300mg"] },
  { id: 59, name: "Linezolid", genericName: "Linezolid", category: "Antibiotic", forms: ["Tab", "Inj"], strengths: ["600mg", "200mg/100ml"] },
  { id: 60, name: "Lizolid", genericName: "Linezolid", category: "Antibiotic", forms: ["Tab", "Inj"], strengths: ["600mg"] },
  { id: 61, name: "Meronem", genericName: "Meropenem", category: "Antibiotic", forms: ["Inj"], strengths: ["500mg", "1g"] },
  { id: 62, name: "Amikacin", genericName: "Amikacin", category: "Antibiotic", forms: ["Inj"], strengths: ["100mg/2ml", "250mg/2ml", "500mg/2ml"] },
  { id: 63, name: "Gentamicin", genericName: "Gentamicin", category: "Antibiotic", forms: ["Inj", "Drop", "Cream"], strengths: ["20mg/2ml", "80mg/2ml", "0.3%"] },
  { id: 64, name: "Piptaz", genericName: "Piperacillin + Tazobactam", category: "Antibiotic", forms: ["Inj"], strengths: ["2.25g", "4.5g"] },
  { id: 65, name: "Nitrofurantoin", genericName: "Nitrofurantoin", category: "Antibiotic", forms: ["Cap"], strengths: ["50mg", "100mg"] },
  { id: 66, name: "Furadantin", genericName: "Nitrofurantoin", category: "Antibiotic", forms: ["Tab"], strengths: ["50mg", "100mg"] },
  { id: 67, name: "Bactrim", genericName: "Sulfamethoxazole + Trimethoprim", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["400mg+80mg", "200mg+40mg/5ml"] },
  { id: 68, name: "Septran", genericName: "Sulfamethoxazole + Trimethoprim", category: "Antibiotic", forms: ["Tab", "Syp"], strengths: ["400mg+80mg", "800mg+160mg"] },
  { id: 69, name: "Rifaximin", genericName: "Rifaximin", category: "Antibiotic", forms: ["Tab"], strengths: ["200mg", "400mg", "550mg"] },
  { id: 70, name: "Xifaxan", genericName: "Rifaximin", category: "Antibiotic", forms: ["Tab"], strengths: ["400mg", "550mg"] },

  // ===== ANTIFUNGALS =====
  { id: 71, name: "Fluconazole", genericName: "Fluconazole", category: "Antifungal", forms: ["Tab", "Cap", "Inj"], strengths: ["50mg", "150mg", "200mg", "2mg/ml"] },
  { id: 72, name: "Zocon", genericName: "Fluconazole", category: "Antifungal", forms: ["Tab", "Lotion"], strengths: ["50mg", "150mg", "200mg", "1%"] },
  { id: 73, name: "Canesten", genericName: "Clotrimazole", category: "Antifungal", forms: ["Cream", "Powder", "Lotion"], strengths: ["1%"] },
  { id: 74, name: "Candid", genericName: "Clotrimazole", category: "Antifungal", forms: ["Cream", "Powder", "Lotion", "Drop"], strengths: ["1%"] },
  { id: 75, name: "Terbinafine", genericName: "Terbinafine", category: "Antifungal", forms: ["Tab", "Cream"], strengths: ["250mg", "1%"] },
  { id: 76, name: "Lamisil", genericName: "Terbinafine", category: "Antifungal", forms: ["Tab", "Cream"], strengths: ["250mg", "1%"] },
  { id: 77, name: "Itraconazole", genericName: "Itraconazole", category: "Antifungal", forms: ["Cap"], strengths: ["100mg", "200mg"] },
  { id: 78, name: "Canditral", genericName: "Itraconazole", category: "Antifungal", forms: ["Cap"], strengths: ["100mg", "200mg"] },
  { id: 79, name: "Ketoconazole", genericName: "Ketoconazole", category: "Antifungal", forms: ["Tab", "Cream", "Lotion"], strengths: ["200mg", "2%"] },
  { id: 80, name: "Nizoral", genericName: "Ketoconazole", category: "Antifungal", forms: ["Tab", "Cream", "Lotion"], strengths: ["200mg", "2%"] },
  { id: 81, name: "Voriconazole", genericName: "Voriconazole", category: "Antifungal", forms: ["Tab", "Inj"], strengths: ["50mg", "200mg"] },
  { id: 82, name: "Amphotericin B", genericName: "Amphotericin B", category: "Antifungal", forms: ["Inj"], strengths: ["50mg"] },
  { id: 83, name: "Griseofulvin", genericName: "Griseofulvin", category: "Antifungal", forms: ["Tab"], strengths: ["125mg", "250mg", "500mg"] },

  // ===== ANTIHISTAMINES & ANTI-ALLERGICS =====
  { id: 84, name: "Cetirizine", genericName: "Cetirizine", category: "Antihistamine", forms: ["Tab", "Syp", "Drop"], strengths: ["5mg", "10mg", "5mg/5ml"] },
  { id: 85, name: "Cetzine", genericName: "Cetirizine", category: "Antihistamine", forms: ["Tab", "Syp"], strengths: ["5mg", "10mg", "5mg/5ml"] },
  { id: 86, name: "Okacet", genericName: "Cetirizine", category: "Antihistamine", forms: ["Tab"], strengths: ["10mg"] },
  { id: 87, name: "Levocet", genericName: "Levocetirizine", category: "Antihistamine", forms: ["Tab", "Syp"], strengths: ["5mg", "2.5mg/5ml"] },
  { id: 88, name: "Xyzal", genericName: "Levocetirizine", category: "Antihistamine", forms: ["Tab", "Syp"], strengths: ["5mg", "2.5mg/5ml"] },
  { id: 89, name: "Montair LC", genericName: "Montelukast + Levocetirizine", category: "Antihistamine/Anti-allergic", forms: ["Tab"], strengths: ["10mg+5mg"] },
  { id: 90, name: "Montek LC", genericName: "Montelukast + Levocetirizine", category: "Antihistamine/Anti-allergic", forms: ["Tab"], strengths: ["10mg+5mg"] },
  { id: 91, name: "Allegra", genericName: "Fexofenadine", category: "Antihistamine", forms: ["Tab", "Susp"], strengths: ["120mg", "180mg", "30mg/5ml"] },
  { id: 92, name: "Fexova", genericName: "Fexofenadine", category: "Antihistamine", forms: ["Tab"], strengths: ["120mg", "180mg"] },
  { id: 93, name: "Avil", genericName: "Pheniramine", category: "Antihistamine", forms: ["Tab", "Inj", "Syp"], strengths: ["25mg", "50mg", "22.75mg/ml", "15mg/5ml"] },
  { id: 94, name: "Atarax", genericName: "Hydroxyzine", category: "Antihistamine", forms: ["Tab", "Syp"], strengths: ["10mg", "25mg", "10mg/5ml"] },
  { id: 95, name: "Loratadine", genericName: "Loratadine", category: "Antihistamine", forms: ["Tab", "Syp"], strengths: ["10mg", "5mg/5ml"] },
  { id: 96, name: "Lorfast", genericName: "Loratadine", category: "Antihistamine", forms: ["Tab"], strengths: ["10mg"] },
  { id: 97, name: "Desloratadine", genericName: "Desloratadine", category: "Antihistamine", forms: ["Tab", "Syp"], strengths: ["5mg", "2.5mg/5ml"] },
  { id: 98, name: "Montair", genericName: "Montelukast", category: "Anti-allergic/Antiasthmatic", forms: ["Tab", "Sachet"], strengths: ["4mg", "5mg", "10mg"] },

  // ===== ANTIHYPERTENSIVES =====
  { id: 99, name: "Telma", genericName: "Telmisartan", category: "Antihypertensive", forms: ["Tab"], strengths: ["20mg", "40mg", "80mg"] },
  { id: 100, name: "Telma H", genericName: "Telmisartan + Hydrochlorothiazide", category: "Antihypertensive", forms: ["Tab"], strengths: ["40mg+12.5mg", "80mg+12.5mg"] },
  { id: 101, name: "Telma AM", genericName: "Telmisartan + Amlodipine", category: "Antihypertensive", forms: ["Tab"], strengths: ["40mg+5mg", "80mg+5mg"] },
  { id: 102, name: "Telmikind", genericName: "Telmisartan", category: "Antihypertensive", forms: ["Tab"], strengths: ["20mg", "40mg", "80mg"] },
  { id: 103, name: "Amlong", genericName: "Amlodipine", category: "Antihypertensive", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg"] },
  { id: 104, name: "Amlodac", genericName: "Amlodipine", category: "Antihypertensive", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg"] },
  { id: 105, name: "Stamlo", genericName: "Amlodipine", category: "Antihypertensive", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg"] },
  { id: 106, name: "Envas", genericName: "Enalapril", category: "Antihypertensive", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg", "20mg"] },
  { id: 107, name: "Ramipril", genericName: "Ramipril", category: "Antihypertensive", forms: ["Cap", "Tab"], strengths: ["1.25mg", "2.5mg", "5mg", "10mg"] },
  { id: 108, name: "Cardace", genericName: "Ramipril", category: "Antihypertensive", forms: ["Tab"], strengths: ["1.25mg", "2.5mg", "5mg", "10mg"] },
  { id: 109, name: "Losar", genericName: "Losartan", category: "Antihypertensive", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 110, name: "Losar H", genericName: "Losartan + Hydrochlorothiazide", category: "Antihypertensive", forms: ["Tab"], strengths: ["50mg+12.5mg", "100mg+25mg"] },
  { id: 111, name: "Covance", genericName: "Losartan", category: "Antihypertensive", forms: ["Tab"], strengths: ["25mg", "50mg"] },
  { id: 112, name: "Olmesar", genericName: "Olmesartan", category: "Antihypertensive", forms: ["Tab"], strengths: ["10mg", "20mg", "40mg"] },
  { id: 113, name: "Olmetec", genericName: "Olmesartan", category: "Antihypertensive", forms: ["Tab"], strengths: ["20mg", "40mg"] },
  { id: 114, name: "Atenolol", genericName: "Atenolol", category: "Antihypertensive/Beta Blocker", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 115, name: "Metolar", genericName: "Metoprolol Succinate", category: "Antihypertensive/Beta Blocker", forms: ["Tab"], strengths: ["12.5mg", "25mg", "50mg", "100mg"] },
  { id: 116, name: "Met XL", genericName: "Metoprolol Succinate", category: "Antihypertensive/Beta Blocker", forms: ["Tab"], strengths: ["12.5mg", "25mg", "50mg", "100mg"] },
  { id: 117, name: "Betaloc", genericName: "Metoprolol Tartrate", category: "Antihypertensive/Beta Blocker", forms: ["Tab", "Inj"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 118, name: "Nebicard", genericName: "Nebivolol", category: "Antihypertensive/Beta Blocker", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg"] },
  { id: 119, name: "Cardivas", genericName: "Carvedilol", category: "Antihypertensive/Beta Blocker", forms: ["Tab"], strengths: ["3.125mg", "6.25mg", "12.5mg", "25mg"] },
  { id: 120, name: "Dilzem", genericName: "Diltiazem", category: "Antihypertensive/Calcium Channel Blocker", forms: ["Tab", "Cap", "Inj"], strengths: ["30mg", "60mg", "90mg", "120mg"] },
  { id: 121, name: "Prazosin", genericName: "Prazosin", category: "Antihypertensive", forms: ["Tab"], strengths: ["1mg", "2mg", "5mg"] },
  { id: 122, name: "Minipress XL", genericName: "Prazosin XL", category: "Antihypertensive", forms: ["Tab"], strengths: ["2.5mg", "5mg"] },
  { id: 123, name: "Clonidine", genericName: "Clonidine", category: "Antihypertensive", forms: ["Tab"], strengths: ["0.1mg", "0.2mg", "0.3mg"] },
  { id: 124, name: "Arkamin", genericName: "Clonidine", category: "Antihypertensive", forms: ["Tab"], strengths: ["0.1mg", "0.2mg"] },
  { id: 125, name: "Cilnidipine", genericName: "Cilnidipine", category: "Antihypertensive", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg"] },
  { id: 126, name: "Cilacar", genericName: "Cilnidipine", category: "Antihypertensive", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg"] },

  // ===== ANTIDIABETICS =====
  { id: 127, name: "Glycomet", genericName: "Metformin", category: "Antidiabetic", forms: ["Tab"], strengths: ["250mg", "500mg", "850mg", "1000mg"] },
  { id: 128, name: "Glycomet GP", genericName: "Metformin + Glimepiride", category: "Antidiabetic", forms: ["Tab"], strengths: ["500mg+1mg", "500mg+2mg", "1000mg+1mg", "1000mg+2mg"] },
  { id: 129, name: "Glucophage", genericName: "Metformin", category: "Antidiabetic", forms: ["Tab"], strengths: ["500mg", "850mg", "1000mg"] },
  { id: 130, name: "Glyciphage", genericName: "Metformin", category: "Antidiabetic", forms: ["Tab"], strengths: ["250mg", "500mg", "850mg"] },
  { id: 131, name: "Amaryl", genericName: "Glimepiride", category: "Antidiabetic", forms: ["Tab"], strengths: ["1mg", "2mg", "3mg", "4mg"] },
  { id: 132, name: "Glimisave", genericName: "Glimepiride", category: "Antidiabetic", forms: ["Tab"], strengths: ["1mg", "2mg"] },
  { id: 133, name: "Amaryl M", genericName: "Glimepiride + Metformin", category: "Antidiabetic", forms: ["Tab"], strengths: ["1mg+500mg", "2mg+500mg", "1mg+1000mg"] },
  { id: 134, name: "Galvus", genericName: "Vildagliptin", category: "Antidiabetic (DPP-4 Inhibitor)", forms: ["Tab"], strengths: ["50mg"] },
  { id: 135, name: "Galvus Met", genericName: "Vildagliptin + Metformin", category: "Antidiabetic", forms: ["Tab"], strengths: ["50mg+500mg", "50mg+850mg", "50mg+1000mg"] },
  { id: 136, name: "Januvia", genericName: "Sitagliptin", category: "Antidiabetic (DPP-4 Inhibitor)", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 137, name: "Janumet", genericName: "Sitagliptin + Metformin", category: "Antidiabetic", forms: ["Tab"], strengths: ["50mg+500mg", "50mg+1000mg"] },
  { id: 138, name: "Trajenta", genericName: "Linagliptin", category: "Antidiabetic (DPP-4 Inhibitor)", forms: ["Tab"], strengths: ["5mg"] },
  { id: 139, name: "Jardiance", genericName: "Empagliflozin", category: "Antidiabetic (SGLT2 Inhibitor)", forms: ["Tab"], strengths: ["10mg", "25mg"] },
  { id: 140, name: "Forxiga", genericName: "Dapagliflozin", category: "Antidiabetic (SGLT2 Inhibitor)", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 141, name: "Invokana", genericName: "Canagliflozin", category: "Antidiabetic (SGLT2 Inhibitor)", forms: ["Tab"], strengths: ["100mg", "300mg"] },
  { id: 142, name: "Daonil", genericName: "Glibenclamide", category: "Antidiabetic", forms: ["Tab"], strengths: ["2.5mg", "5mg"] },
  { id: 143, name: "Glynase", genericName: "Glipizide", category: "Antidiabetic", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 144, name: "Pioglitazone", genericName: "Pioglitazone", category: "Antidiabetic", forms: ["Tab"], strengths: ["15mg", "30mg", "45mg"] },
  { id: 145, name: "Vogli GM", genericName: "Voglibose + Metformin + Glimepiride", category: "Antidiabetic", forms: ["Tab"], strengths: ["0.2mg+500mg+1mg", "0.3mg+500mg+2mg"] },
  { id: 146, name: "Voglibose", genericName: "Voglibose", category: "Antidiabetic", forms: ["Tab"], strengths: ["0.2mg", "0.3mg"] },
  { id: 147, name: "Lantus", genericName: "Insulin Glargine", category: "Antidiabetic (Insulin)", forms: ["Inj"], strengths: ["100IU/ml"] },
  { id: 148, name: "Mixtard", genericName: "Human Insulin 30/70", category: "Antidiabetic (Insulin)", forms: ["Inj"], strengths: ["40IU/ml", "100IU/ml"] },
  { id: 149, name: "Actrapid", genericName: "Soluble Insulin (Human)", category: "Antidiabetic (Insulin)", forms: ["Inj"], strengths: ["40IU/ml", "100IU/ml"] },
  { id: 150, name: "Humalog", genericName: "Insulin Lispro", category: "Antidiabetic (Insulin)", forms: ["Inj"], strengths: ["100IU/ml"] },
  { id: 151, name: "Teneligliptin", genericName: "Teneligliptin", category: "Antidiabetic (DPP-4 Inhibitor)", forms: ["Tab"], strengths: ["20mg"] },

  // ===== GASTROINTESTINAL =====
  { id: 152, name: "Pan", genericName: "Pantoprazole", category: "GI/Antacid (PPI)", forms: ["Tab", "Inj"], strengths: ["20mg", "40mg", "40mg vial"] },
  { id: 153, name: "Pan D", genericName: "Pantoprazole + Domperidone", category: "GI/Antacid", forms: ["Cap"], strengths: ["40mg+30mg"] },
  { id: 154, name: "Pantop", genericName: "Pantoprazole", category: "GI/Antacid (PPI)", forms: ["Tab", "Inj"], strengths: ["20mg", "40mg"] },
  { id: 155, name: "Pantop D", genericName: "Pantoprazole + Domperidone", category: "GI/Antacid", forms: ["Cap"], strengths: ["40mg+30mg"] },
  { id: 156, name: "Rantac", genericName: "Ranitidine", category: "GI/Antacid (H2 Blocker)", forms: ["Tab", "Syp", "Inj"], strengths: ["150mg", "300mg", "75mg/5ml", "25mg/ml"] },
  { id: 157, name: "Zinetac", genericName: "Ranitidine", category: "GI/Antacid (H2 Blocker)", forms: ["Tab", "Syp"], strengths: ["150mg", "300mg"] },
  { id: 158, name: "Omez", genericName: "Omeprazole", category: "GI/Antacid (PPI)", forms: ["Cap", "Inj"], strengths: ["20mg", "40mg"] },
  { id: 159, name: "Omez D", genericName: "Omeprazole + Domperidone", category: "GI/Antacid", forms: ["Cap"], strengths: ["20mg+10mg"] },
  { id: 160, name: "Nexpro", genericName: "Esomeprazole", category: "GI/Antacid (PPI)", forms: ["Tab", "Inj"], strengths: ["20mg", "40mg"] },
  { id: 161, name: "Nexpro RD", genericName: "Esomeprazole + Domperidone", category: "GI/Antacid", forms: ["Cap"], strengths: ["20mg+30mg", "40mg+30mg"] },
  { id: 162, name: "Rablet", genericName: "Rabeprazole", category: "GI/Antacid (PPI)", forms: ["Tab"], strengths: ["10mg", "20mg"] },
  { id: 163, name: "Rablet D", genericName: "Rabeprazole + Domperidone", category: "GI/Antacid", forms: ["Cap"], strengths: ["20mg+30mg"] },
  { id: 164, name: "Razo", genericName: "Rabeprazole", category: "GI/Antacid (PPI)", forms: ["Tab"], strengths: ["10mg", "20mg"] },
  { id: 165, name: "Razo D", genericName: "Rabeprazole + Domperidone", category: "GI/Antacid", forms: ["Cap"], strengths: ["20mg+30mg"] },
  { id: 166, name: "Domperidone", genericName: "Domperidone", category: "GI/Antiemetic", forms: ["Tab", "Susp"], strengths: ["10mg", "5mg/5ml"] },
  { id: 167, name: "Domstal", genericName: "Domperidone", category: "GI/Antiemetic", forms: ["Tab", "Susp"], strengths: ["10mg", "5mg/5ml"] },
  { id: 168, name: "Emeset", genericName: "Ondansetron", category: "Antiemetic", forms: ["Tab", "Inj", "Syp"], strengths: ["4mg", "8mg", "2mg/ml", "2mg/5ml"] },
  { id: 169, name: "Perinorm", genericName: "Metoclopramide", category: "GI/Antiemetic", forms: ["Tab", "Inj", "Syp"], strengths: ["10mg", "5mg/ml", "5mg/5ml"] },
  { id: 170, name: "Sucralfate", genericName: "Sucralfate", category: "GI/Antacid", forms: ["Syp", "Tab", "Gel"], strengths: ["1g/10ml", "500mg", "1g"] },
  { id: 171, name: "Mucaine Gel", genericName: "Aluminium Hydroxide + Magnesium Hydroxide + Oxetacaine", category: "GI/Antacid", forms: ["Gel", "Syp"], strengths: ["0.29g+0.98g+10mg/5ml"] },
  { id: 172, name: "Gelusil MPS", genericName: "Magaldrate + Simethicone", category: "GI/Antacid", forms: ["Syp", "Tab"], strengths: ["540mg+50mg/5ml"] },
  { id: 173, name: "Digene", genericName: "Magaldrate + Simethicone", category: "GI/Antacid", forms: ["Tab", "Gel", "Syp"], strengths: ["480mg+20mg"] },
  { id: 174, name: "Duphalac", genericName: "Lactulose", category: "GI/Laxative", forms: ["Syp"], strengths: ["10g/15ml"] },
  { id: 175, name: "Cremaffin", genericName: "Liquid Paraffin + Milk of Magnesia", category: "GI/Laxative", forms: ["Syp"], strengths: ["3.75ml+11.25ml/15ml"] },
  { id: 176, name: "Dulcoflex", genericName: "Bisacodyl", category: "GI/Laxative", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 177, name: "Isabgol", genericName: "Psyllium Husk", category: "GI/Laxative", forms: ["Powder"], strengths: ["3.5g/sachet"] },
  { id: 178, name: "Lopeamide", genericName: "Loperamide", category: "GI/Antidiarrhoeal", forms: ["Cap", "Tab"], strengths: ["2mg"] },
  { id: 179, name: "Imodium", genericName: "Loperamide", category: "GI/Antidiarrhoeal", forms: ["Cap"], strengths: ["2mg"] },
  { id: 180, name: "Econorm", genericName: "Saccharomyces boulardii", category: "GI/Probiotic", forms: ["Cap", "Sachet"], strengths: ["250mg"] },
  { id: 181, name: "Sporlac", genericName: "Lactic Acid Bacillus", category: "GI/Probiotic", forms: ["Tab", "Sachet"], strengths: ["60 million spores", "120 million spores"] },
  { id: 182, name: "Enterogermina", genericName: "Bacillus clausii", category: "GI/Probiotic", forms: ["Cap", "Susp"], strengths: ["2 billion spores/5ml"] },
  { id: 183, name: "ORS", genericName: "Oral Rehydration Salts", category: "GI/Electrolyte", forms: ["Powder", "Sachet"], strengths: ["WHO formula"] },
  { id: 184, name: "Electral", genericName: "Oral Rehydration Salts", category: "GI/Electrolyte", forms: ["Powder", "Sachet"], strengths: ["21.8g/sachet"] },
  { id: 185, name: "Ursocol", genericName: "Ursodeoxycholic Acid", category: "GI/Hepatoprotective", forms: ["Tab"], strengths: ["150mg", "300mg"] },

  // ===== CARDIAC / LIPID-LOWERING =====
  { id: 186, name: "Ecosprin", genericName: "Aspirin", category: "Antiplatelet/Cardiac", forms: ["Tab"], strengths: ["75mg", "150mg", "325mg"] },
  { id: 187, name: "Ecosprin AV", genericName: "Aspirin + Atorvastatin", category: "Cardiac", forms: ["Cap"], strengths: ["75mg+10mg", "75mg+20mg", "150mg+10mg", "150mg+20mg"] },
  { id: 188, name: "Ecosprin Gold", genericName: "Aspirin + Atorvastatin + Clopidogrel", category: "Cardiac", forms: ["Cap"], strengths: ["75mg+10mg+75mg", "75mg+20mg+75mg"] },
  { id: 189, name: "Clopitab", genericName: "Clopidogrel", category: "Antiplatelet", forms: ["Tab"], strengths: ["75mg", "150mg"] },
  { id: 190, name: "Clopilet", genericName: "Clopidogrel", category: "Antiplatelet", forms: ["Tab"], strengths: ["75mg"] },
  { id: 191, name: "Plavix", genericName: "Clopidogrel", category: "Antiplatelet", forms: ["Tab"], strengths: ["75mg"] },
  { id: 192, name: "Atorva", genericName: "Atorvastatin", category: "Lipid-Lowering (Statin)", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg", "40mg", "80mg"] },
  { id: 193, name: "Atocor", genericName: "Atorvastatin", category: "Lipid-Lowering (Statin)", forms: ["Tab"], strengths: ["10mg", "20mg", "40mg"] },
  { id: 194, name: "Lipitor", genericName: "Atorvastatin", category: "Lipid-Lowering (Statin)", forms: ["Tab"], strengths: ["10mg", "20mg", "40mg", "80mg"] },
  { id: 195, name: "Rosulip", genericName: "Rosuvastatin", category: "Lipid-Lowering (Statin)", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg", "40mg"] },
  { id: 196, name: "Crestor", genericName: "Rosuvastatin", category: "Lipid-Lowering (Statin)", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg"] },
  { id: 197, name: "Rozavel", genericName: "Rosuvastatin", category: "Lipid-Lowering (Statin)", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg", "40mg"] },
  { id: 198, name: "Fibator", genericName: "Atorvastatin + Fenofibrate", category: "Lipid-Lowering", forms: ["Tab"], strengths: ["10mg+145mg", "10mg+160mg"] },
  { id: 199, name: "Fenofibrate", genericName: "Fenofibrate", category: "Lipid-Lowering", forms: ["Tab", "Cap"], strengths: ["145mg", "160mg", "200mg"] },
  { id: 200, name: "Lipikind", genericName: "Fenofibrate", category: "Lipid-Lowering", forms: ["Tab"], strengths: ["145mg", "160mg"] },
  { id: 201, name: "Sorbitrate", genericName: "Isosorbide Dinitrate", category: "Cardiac/Antianginal", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 202, name: "Mono Isordil", genericName: "Isosorbide Mononitrate", category: "Cardiac/Antianginal", forms: ["Tab"], strengths: ["10mg", "20mg", "30mg", "60mg"] },
  { id: 203, name: "Nitroglycerin", genericName: "Glyceryl Trinitrate", category: "Cardiac/Antianginal", forms: ["Tab", "Spray", "Patch", "Inj"], strengths: ["0.5mg", "0.4mg/spray", "5mg/24hr", "5mg/ml"] },
  { id: 204, name: "Digoxin", genericName: "Digoxin", category: "Cardiac Glycoside", forms: ["Tab", "Inj"], strengths: ["0.25mg", "0.5mg/2ml"] },
  { id: 205, name: "Lanoxin", genericName: "Digoxin", category: "Cardiac Glycoside", forms: ["Tab"], strengths: ["0.25mg"] },
  { id: 206, name: "Amiodarone", genericName: "Amiodarone", category: "Cardiac/Antiarrhythmic", forms: ["Tab", "Inj"], strengths: ["100mg", "200mg", "150mg/3ml"] },
  { id: 207, name: "Cordarone", genericName: "Amiodarone", category: "Cardiac/Antiarrhythmic", forms: ["Tab", "Inj"], strengths: ["200mg"] },
  { id: 208, name: "Ivabrad", genericName: "Ivabradine", category: "Cardiac", forms: ["Tab"], strengths: ["5mg", "7.5mg"] },
  { id: 209, name: "Ranexa", genericName: "Ranolazine", category: "Cardiac/Antianginal", forms: ["Tab"], strengths: ["500mg", "1000mg"] },
  { id: 210, name: "Trimetazidine", genericName: "Trimetazidine", category: "Cardiac/Antianginal", forms: ["Tab"], strengths: ["20mg", "35mg"] },

  // ===== ANTICOAGULANTS =====
  { id: 211, name: "Acitrom", genericName: "Acenocoumarol (Nicoumalone)", category: "Anticoagulant", forms: ["Tab"], strengths: ["0.5mg", "1mg", "2mg", "3mg", "4mg"] },
  { id: 212, name: "Warf", genericName: "Warfarin", category: "Anticoagulant", forms: ["Tab"], strengths: ["1mg", "2mg", "3mg", "5mg"] },
  { id: 213, name: "Heparin", genericName: "Heparin Sodium", category: "Anticoagulant", forms: ["Inj"], strengths: ["5000IU/ml", "25000IU/5ml"] },
  { id: 214, name: "Clexane", genericName: "Enoxaparin", category: "Anticoagulant", forms: ["Inj"], strengths: ["20mg/0.2ml", "40mg/0.4ml", "60mg/0.6ml"] },
  { id: 215, name: "Xarelto", genericName: "Rivaroxaban", category: "Anticoagulant (NOAC)", forms: ["Tab"], strengths: ["2.5mg", "10mg", "15mg", "20mg"] },
  { id: 216, name: "Eliquis", genericName: "Apixaban", category: "Anticoagulant (NOAC)", forms: ["Tab"], strengths: ["2.5mg", "5mg"] },
  { id: 217, name: "Pradaxa", genericName: "Dabigatran", category: "Anticoagulant (NOAC)", forms: ["Cap"], strengths: ["75mg", "110mg", "150mg"] },

  // ===== RESPIRATORY / ANTIASTHMATICS =====
  { id: 218, name: "Asthalin", genericName: "Salbutamol", category: "Respiratory/Bronchodilator", forms: ["Inhaler", "Tab", "Syp", "Inj"], strengths: ["100mcg/puff", "2mg", "4mg", "2mg/5ml"] },
  { id: 219, name: "Deriphyllin", genericName: "Etophylline + Theophylline", category: "Respiratory/Bronchodilator", forms: ["Tab", "Inj"], strengths: ["77mg+23mg", "169.4mg+50.6mg/2ml"] },
  { id: 220, name: "Foracort", genericName: "Budesonide + Formoterol", category: "Respiratory/Antiasthmatic", forms: ["Inhaler"], strengths: ["100mcg+6mcg", "200mcg+6mcg", "400mcg+6mcg"] },
  { id: 221, name: "Budecort", genericName: "Budesonide", category: "Respiratory/Antiasthmatic", forms: ["Inhaler"], strengths: ["100mcg", "200mcg", "400mcg"] },
  { id: 222, name: "Seroflo", genericName: "Salmeterol + Fluticasone", category: "Respiratory/Antiasthmatic", forms: ["Inhaler"], strengths: ["25mcg+50mcg", "25mcg+125mcg", "25mcg+250mcg"] },
  { id: 223, name: "Duolin", genericName: "Ipratropium + Levosalbutamol", category: "Respiratory/Bronchodilator", forms: ["Inhaler", "Solution"], strengths: ["20mcg+50mcg/puff", "500mcg+1.25mg/2.5ml"] },
  { id: 224, name: "Tiova", genericName: "Tiotropium", category: "Respiratory/Bronchodilator", forms: ["Inhaler", "Cap"], strengths: ["9mcg/puff", "18mcg"] },
  { id: 225, name: "Montek", genericName: "Montelukast", category: "Respiratory/Antiasthmatic", forms: ["Tab", "Sachet"], strengths: ["4mg", "5mg", "10mg"] },
  { id: 226, name: "Alex", genericName: "Phenylephrine + Chlorpheniramine + Dextromethorphan", category: "Respiratory/Cough", forms: ["Syp"], strengths: ["5mg+2mg+10mg/5ml"] },
  { id: 227, name: "Benadryl", genericName: "Diphenhydramine + Ammonium Chloride + Sodium Citrate", category: "Respiratory/Cough", forms: ["Syp"], strengths: ["14mg+138mg+57mg/5ml"] },
  { id: 228, name: "Grilinctus", genericName: "Dextromethorphan + Phenylephrine + Chlorpheniramine", category: "Respiratory/Cough", forms: ["Syp"], strengths: ["10mg+5mg+2mg/5ml"] },
  { id: 229, name: "Ambrodil S", genericName: "Ambroxol + Salbutamol + Guaifenesin", category: "Respiratory/Mucolytic", forms: ["Syp"], strengths: ["15mg+1mg+50mg/5ml"] },
  { id: 230, name: "Mucinac", genericName: "Acetylcysteine (NAC)", category: "Respiratory/Mucolytic", forms: ["Tab", "Sachet"], strengths: ["200mg", "600mg"] },
  { id: 231, name: "Ascoril LS", genericName: "Ambroxol + Levosalbutamol + Guaifenesin", category: "Respiratory/Mucolytic", forms: ["Syp"], strengths: ["30mg+1mg+50mg/5ml"] },
  { id: 232, name: "Ascoril D Plus", genericName: "Dextromethorphan + Phenylephrine + Chlorpheniramine", category: "Respiratory/Cough", forms: ["Syp"], strengths: ["10mg+5mg+2mg/5ml"] },
  { id: 233, name: "Sinarest", genericName: "Paracetamol + Phenylephrine + Chlorpheniramine + Caffeine", category: "Respiratory/Cold & Flu", forms: ["Tab"], strengths: ["500mg+10mg+2mg+30mg"] },
  { id: 234, name: "Cheston Cold", genericName: "Paracetamol + Phenylephrine + Cetirizine", category: "Respiratory/Cold & Flu", forms: ["Tab"], strengths: ["325mg+10mg+5mg"] },
  { id: 235, name: "Otrivin", genericName: "Xylometazoline", category: "Respiratory/Nasal Decongestant", forms: ["Drop", "Spray"], strengths: ["0.05%", "0.1%"] },
  { id: 236, name: "Nasivion", genericName: "Oxymetazoline", category: "Respiratory/Nasal Decongestant", forms: ["Drop", "Spray"], strengths: ["0.01%", "0.025%", "0.05%"] },
  { id: 237, name: "Levolin", genericName: "Levosalbutamol", category: "Respiratory/Bronchodilator", forms: ["Inhaler", "Syp"], strengths: ["50mcg/puff", "1mg/5ml"] },
  { id: 238, name: "Flutivate", genericName: "Fluticasone Propionate", category: "Respiratory/Corticosteroid", forms: ["Inhaler", "Spray"], strengths: ["125mcg", "250mcg", "50mcg/spray"] },

  // ===== CORTICOSTEROIDS =====
  { id: 239, name: "Wysolone", genericName: "Prednisolone", category: "Corticosteroid", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg", "40mg"] },
  { id: 240, name: "Omnacortil", genericName: "Prednisolone", category: "Corticosteroid", forms: ["Tab", "Syp"], strengths: ["5mg", "10mg", "20mg", "5mg/5ml"] },
  { id: 241, name: "Defcort", genericName: "Deflazacort", category: "Corticosteroid", forms: ["Tab"], strengths: ["6mg", "12mg", "24mg", "30mg"] },
  { id: 242, name: "Dexona", genericName: "Dexamethasone", category: "Corticosteroid", forms: ["Tab", "Inj"], strengths: ["0.5mg", "4mg/ml", "8mg/2ml"] },
  { id: 243, name: "Betnesol", genericName: "Betamethasone", category: "Corticosteroid", forms: ["Tab", "Inj", "Drop"], strengths: ["0.5mg", "4mg/ml", "0.1%"] },
  { id: 244, name: "Kenacort", genericName: "Triamcinolone", category: "Corticosteroid", forms: ["Inj", "Tab"], strengths: ["10mg/ml", "40mg/ml", "4mg"] },
  { id: 245, name: "Hydrocortisone", genericName: "Hydrocortisone", category: "Corticosteroid", forms: ["Tab", "Inj", "Cream"], strengths: ["10mg", "20mg", "100mg vial", "1%"] },
  { id: 246, name: "Methylprednisolone", genericName: "Methylprednisolone", category: "Corticosteroid", forms: ["Tab", "Inj"], strengths: ["4mg", "8mg", "16mg", "40mg vial", "125mg vial"] },
  { id: 247, name: "Solu-Medrol", genericName: "Methylprednisolone Sodium Succinate", category: "Corticosteroid", forms: ["Inj"], strengths: ["40mg", "125mg", "500mg", "1g"] },
  { id: 248, name: "Budecort Respules", genericName: "Budesonide", category: "Corticosteroid", forms: ["Solution"], strengths: ["0.5mg/2ml", "1mg/2ml"] },

  // ===== VITAMINS & SUPPLEMENTS =====
  { id: 249, name: "Shelcal", genericName: "Calcium Carbonate + Vitamin D3", category: "Vitamin/Supplement", forms: ["Tab"], strengths: ["500mg+250IU"] },
  { id: 250, name: "Shelcal HD", genericName: "Calcium Carbonate + Vitamin D3", category: "Vitamin/Supplement", forms: ["Tab"], strengths: ["500mg+1000IU"] },
  { id: 251, name: "Shelcal OS", genericName: "Calcium + Vitamin D3 + Zinc + Magnesium", category: "Vitamin/Supplement", forms: ["Tab"], strengths: ["500mg+200IU+7.5mg+50mg"] },
  { id: 252, name: "Calcimax", genericName: "Calcium + Vitamin D3", category: "Vitamin/Supplement", forms: ["Tab"], strengths: ["500mg+250IU"] },
  { id: 253, name: "Calcirol", genericName: "Cholecalciferol (Vitamin D3)", category: "Vitamin/Supplement", forms: ["Cap", "Sachet"], strengths: ["60000IU"] },
  { id: 254, name: "D3 Must", genericName: "Cholecalciferol (Vitamin D3)", category: "Vitamin/Supplement", forms: ["Cap", "Sachet"], strengths: ["60000IU"] },
  { id: 255, name: "Uprise D3", genericName: "Cholecalciferol (Vitamin D3)", category: "Vitamin/Supplement", forms: ["Tab", "Sachet"], strengths: ["1000IU", "2000IU", "60000IU"] },
  { id: 256, name: "Becosules", genericName: "B-Complex + Vitamin C", category: "Vitamin/Supplement", forms: ["Cap", "Syp"], strengths: ["Multivitamin"] },
  { id: 257, name: "Becosules Z", genericName: "B-Complex + Vitamin C + Zinc", category: "Vitamin/Supplement", forms: ["Cap"], strengths: ["Multivitamin + Zinc"] },
  { id: 258, name: "Supradyn", genericName: "Multivitamin + Multimineral", category: "Vitamin/Supplement", forms: ["Tab"], strengths: ["Multivitamin"] },
  { id: 259, name: "Zincovit", genericName: "Multivitamin + Multimineral + Zinc", category: "Vitamin/Supplement", forms: ["Tab", "Syp"], strengths: ["Multivitamin"] },
  { id: 260, name: "Limcee", genericName: "Vitamin C (Ascorbic Acid)", category: "Vitamin/Supplement", forms: ["Tab"], strengths: ["100mg", "500mg"] },
  { id: 261, name: "Neurobion Forte", genericName: "Vitamin B1 + B6 + B12", category: "Vitamin/Supplement", forms: ["Tab", "Inj"], strengths: ["100mg+200mg+200mcg"] },
  { id: 262, name: "Methylcobal", genericName: "Methylcobalamin", category: "Vitamin/Supplement", forms: ["Tab", "Inj"], strengths: ["500mcg", "1500mcg", "1mg/ml"] },
  { id: 263, name: "Mecobalamin", genericName: "Methylcobalamin", category: "Vitamin/Supplement", forms: ["Tab", "Inj", "Cap"], strengths: ["500mcg", "1500mcg"] },
  { id: 264, name: "Nurokind Plus", genericName: "Methylcobalamin + Alpha Lipoic Acid + Pyridoxine + Folic Acid", category: "Vitamin/Supplement", forms: ["Tab", "Cap"], strengths: ["1500mcg+100mg+3mg+1.5mg"] },
  { id: 265, name: "Folvite", genericName: "Folic Acid", category: "Vitamin/Supplement", forms: ["Tab"], strengths: ["5mg"] },
  { id: 266, name: "Autrin", genericName: "Ferrous Fumarate + Folic Acid + Zinc", category: "Iron Supplement", forms: ["Cap"], strengths: ["300mg+1.5mg+22.5mg"] },
  { id: 267, name: "Orofer XT", genericName: "Ferrous Ascorbate + Folic Acid", category: "Iron Supplement", forms: ["Tab"], strengths: ["100mg+1.5mg"] },
  { id: 268, name: "Livogen", genericName: "Ferrous Fumarate + Folic Acid", category: "Iron Supplement", forms: ["Tab", "Cap"], strengths: ["152mg+0.5mg"] },
  { id: 269, name: "Dexorange", genericName: "Ferric Ammonium Citrate + Folic Acid + Cyanocobalamin", category: "Iron Supplement", forms: ["Syp", "Cap"], strengths: ["160mg+0.5mg+7.5mcg/5ml"] },
  { id: 270, name: "Evion", genericName: "Vitamin E (Tocopherol)", category: "Vitamin/Supplement", forms: ["Cap"], strengths: ["200mg", "400mg"] },
  { id: 271, name: "A to Z NS", genericName: "Multivitamin + Multimineral + Antioxidant", category: "Vitamin/Supplement", forms: ["Tab"], strengths: ["Multivitamin"] },
  { id: 272, name: "Revital", genericName: "Multivitamin + Ginseng", category: "Vitamin/Supplement", forms: ["Cap"], strengths: ["Multivitamin"] },
  { id: 273, name: "Zinc", genericName: "Zinc Sulphate", category: "Vitamin/Supplement", forms: ["Tab", "Syp"], strengths: ["20mg", "10mg/5ml"] },
  { id: 274, name: "Potklor", genericName: "Potassium Chloride", category: "Electrolyte Supplement", forms: ["Syp"], strengths: ["1.5g/15ml"] },

  // ===== THYROID =====
  { id: 275, name: "Thyronorm", genericName: "Levothyroxine", category: "Thyroid", forms: ["Tab"], strengths: ["12.5mcg", "25mcg", "50mcg", "75mcg", "88mcg", "100mcg", "112mcg", "125mcg", "150mcg"] },
  { id: 276, name: "Eltroxin", genericName: "Levothyroxine", category: "Thyroid", forms: ["Tab"], strengths: ["25mcg", "50mcg", "75mcg", "100mcg"] },
  { id: 277, name: "Thyrox", genericName: "Levothyroxine", category: "Thyroid", forms: ["Tab"], strengths: ["12.5mcg", "25mcg", "50mcg", "75mcg", "100mcg", "125mcg"] },
  { id: 278, name: "Neomercazole", genericName: "Carbimazole", category: "Antithyroid", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg"] },
  { id: 279, name: "PTU", genericName: "Propylthiouracil", category: "Antithyroid", forms: ["Tab"], strengths: ["50mg", "100mg"] },

  // ===== PSYCHIATRIC / CNS =====
  { id: 280, name: "Nexito", genericName: "Escitalopram", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg"] },
  { id: 281, name: "Nexito Plus", genericName: "Escitalopram + Clonazepam", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["5mg+0.25mg", "10mg+0.5mg", "20mg+0.5mg"] },
  { id: 282, name: "Cipralex", genericName: "Escitalopram", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg"] },
  { id: 283, name: "Fluoxetine", genericName: "Fluoxetine", category: "Psychiatric/Antidepressant", forms: ["Cap"], strengths: ["10mg", "20mg", "40mg", "60mg"] },
  { id: 284, name: "Fludac", genericName: "Fluoxetine", category: "Psychiatric/Antidepressant", forms: ["Cap"], strengths: ["10mg", "20mg"] },
  { id: 285, name: "Sertraline", genericName: "Sertraline", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 286, name: "Daxid", genericName: "Sertraline", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 287, name: "Venlor XR", genericName: "Venlafaxine", category: "Psychiatric/Antidepressant", forms: ["Cap"], strengths: ["37.5mg", "75mg", "150mg"] },
  { id: 288, name: "Duloxetine", genericName: "Duloxetine", category: "Psychiatric/Antidepressant", forms: ["Cap"], strengths: ["20mg", "30mg", "60mg"] },
  { id: 289, name: "Duzela", genericName: "Duloxetine", category: "Psychiatric/Antidepressant", forms: ["Cap"], strengths: ["20mg", "30mg", "60mg"] },
  { id: 290, name: "Mirtazapine", genericName: "Mirtazapine", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["7.5mg", "15mg", "30mg"] },
  { id: 291, name: "Amitriptyline", genericName: "Amitriptyline", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["10mg", "25mg", "75mg"] },
  { id: 292, name: "Tryptomer", genericName: "Amitriptyline", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["10mg", "25mg", "75mg"] },
  { id: 293, name: "Bupropion", genericName: "Bupropion", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["150mg", "300mg"] },
  { id: 294, name: "Alprazolam", genericName: "Alprazolam", category: "Psychiatric/Anxiolytic", forms: ["Tab"], strengths: ["0.25mg", "0.5mg", "1mg"] },
  { id: 295, name: "Alprax", genericName: "Alprazolam", category: "Psychiatric/Anxiolytic", forms: ["Tab"], strengths: ["0.25mg", "0.5mg", "1mg"] },
  { id: 296, name: "Clonazepam", genericName: "Clonazepam", category: "Psychiatric/Anxiolytic", forms: ["Tab", "Drop"], strengths: ["0.25mg", "0.5mg", "1mg", "2mg"] },
  { id: 297, name: "Clonotril", genericName: "Clonazepam", category: "Psychiatric/Anxiolytic", forms: ["Tab"], strengths: ["0.25mg", "0.5mg", "1mg", "2mg"] },
  { id: 298, name: "Lorazepam", genericName: "Lorazepam", category: "Psychiatric/Anxiolytic", forms: ["Tab", "Inj"], strengths: ["1mg", "2mg", "2mg/ml"] },
  { id: 299, name: "Diazepam", genericName: "Diazepam", category: "Psychiatric/Anxiolytic", forms: ["Tab", "Inj"], strengths: ["2mg", "5mg", "10mg", "5mg/ml"] },
  { id: 300, name: "Calmpose", genericName: "Diazepam", category: "Psychiatric/Anxiolytic", forms: ["Tab", "Inj"], strengths: ["5mg", "10mg", "10mg/2ml"] },
  { id: 301, name: "Olanzapine", genericName: "Olanzapine", category: "Psychiatric/Antipsychotic", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg", "15mg"] },
  { id: 302, name: "Oleanz", genericName: "Olanzapine", category: "Psychiatric/Antipsychotic", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg"] },
  { id: 303, name: "Risperidone", genericName: "Risperidone", category: "Psychiatric/Antipsychotic", forms: ["Tab", "Syp"], strengths: ["1mg", "2mg", "3mg", "4mg", "1mg/ml"] },
  { id: 304, name: "Sizodon", genericName: "Risperidone", category: "Psychiatric/Antipsychotic", forms: ["Tab"], strengths: ["1mg", "2mg", "3mg"] },
  { id: 305, name: "Quetiapine", genericName: "Quetiapine", category: "Psychiatric/Antipsychotic", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg", "200mg", "300mg"] },
  { id: 306, name: "Qutan", genericName: "Quetiapine", category: "Psychiatric/Antipsychotic", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg", "200mg"] },
  { id: 307, name: "Aripiprazole", genericName: "Aripiprazole", category: "Psychiatric/Antipsychotic", forms: ["Tab"], strengths: ["5mg", "10mg", "15mg", "20mg", "30mg"] },
  { id: 308, name: "Lithium", genericName: "Lithium Carbonate", category: "Psychiatric/Mood Stabilizer", forms: ["Tab", "Cap"], strengths: ["300mg", "450mg"] },
  { id: 309, name: "Lithosun", genericName: "Lithium Carbonate", category: "Psychiatric/Mood Stabilizer", forms: ["Tab"], strengths: ["300mg"] },
  { id: 310, name: "Valproate", genericName: "Sodium Valproate", category: "Psychiatric/Antiepileptic", forms: ["Tab", "Syp"], strengths: ["200mg", "300mg", "500mg", "200mg/5ml"] },
  { id: 311, name: "Encorate", genericName: "Sodium Valproate", category: "Psychiatric/Antiepileptic", forms: ["Tab", "Syp"], strengths: ["200mg", "300mg", "500mg"] },
  { id: 312, name: "Encorate Chrono", genericName: "Sodium Valproate + Valproic Acid", category: "Psychiatric/Antiepileptic", forms: ["Tab"], strengths: ["200mg", "300mg", "500mg"] },
  { id: 313, name: "Carbamazepine", genericName: "Carbamazepine", category: "Psychiatric/Antiepileptic", forms: ["Tab", "Syp"], strengths: ["100mg", "200mg", "400mg", "100mg/5ml"] },
  { id: 314, name: "Tegrital", genericName: "Carbamazepine", category: "Psychiatric/Antiepileptic", forms: ["Tab"], strengths: ["100mg", "200mg", "400mg"] },
  { id: 315, name: "Lamotrigine", genericName: "Lamotrigine", category: "Psychiatric/Antiepileptic", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg", "200mg"] },
  { id: 316, name: "Lamictal", genericName: "Lamotrigine", category: "Psychiatric/Antiepileptic", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 317, name: "Phenytoin", genericName: "Phenytoin", category: "Psychiatric/Antiepileptic", forms: ["Tab", "Inj", "Syp"], strengths: ["50mg", "100mg", "300mg", "50mg/ml", "30mg/5ml"] },
  { id: 318, name: "Eptoin", genericName: "Phenytoin", category: "Psychiatric/Antiepileptic", forms: ["Tab", "Inj"], strengths: ["100mg", "300mg"] },
  { id: 319, name: "Levetiracetam", genericName: "Levetiracetam", category: "Psychiatric/Antiepileptic", forms: ["Tab", "Syp"], strengths: ["250mg", "500mg", "750mg", "1000mg", "100mg/ml"] },
  { id: 320, name: "Levera", genericName: "Levetiracetam", category: "Psychiatric/Antiepileptic", forms: ["Tab"], strengths: ["250mg", "500mg", "750mg"] },
  { id: 321, name: "Gabapentin", genericName: "Gabapentin", category: "Psychiatric/Antiepileptic", forms: ["Cap", "Tab"], strengths: ["100mg", "300mg", "400mg", "600mg", "800mg"] },
  { id: 322, name: "Gabapin", genericName: "Gabapentin", category: "Psychiatric/Antiepileptic", forms: ["Cap"], strengths: ["100mg", "300mg", "400mg"] },
  { id: 323, name: "Pregabalin", genericName: "Pregabalin", category: "Psychiatric/Neuropathic Pain", forms: ["Cap"], strengths: ["50mg", "75mg", "100mg", "150mg", "300mg"] },
  { id: 324, name: "Pregabalin M", genericName: "Pregabalin + Methylcobalamin", category: "Neuropathic Pain", forms: ["Cap"], strengths: ["75mg+750mcg", "75mg+1500mcg"] },
  { id: 325, name: "Pregalin", genericName: "Pregabalin", category: "Psychiatric/Neuropathic Pain", forms: ["Cap"], strengths: ["75mg", "150mg"] },
  { id: 326, name: "Zolpidem", genericName: "Zolpidem", category: "Psychiatric/Sedative-Hypnotic", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 327, name: "Stilnox", genericName: "Zolpidem", category: "Psychiatric/Sedative-Hypnotic", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 328, name: "Etizolam", genericName: "Etizolam", category: "Psychiatric/Anxiolytic", forms: ["Tab"], strengths: ["0.25mg", "0.5mg", "1mg"] },
  { id: 329, name: "Etilaam", genericName: "Etizolam", category: "Psychiatric/Anxiolytic", forms: ["Tab"], strengths: ["0.25mg", "0.5mg", "1mg"] },
  { id: 330, name: "Chlorpromazine", genericName: "Chlorpromazine", category: "Psychiatric/Antipsychotic", forms: ["Tab", "Inj"], strengths: ["25mg", "50mg", "100mg", "25mg/ml"] },
  { id: 331, name: "Haloperidol", genericName: "Haloperidol", category: "Psychiatric/Antipsychotic", forms: ["Tab", "Inj"], strengths: ["1.5mg", "5mg", "10mg", "5mg/ml"] },

  // ===== DERMATOLOGY =====
  { id: 332, name: "Betnovate", genericName: "Betamethasone Valerate", category: "Dermatology/Corticosteroid", forms: ["Cream", "Oint", "Lotion"], strengths: ["0.1%"] },
  { id: 333, name: "Betnovate N", genericName: "Betamethasone + Neomycin", category: "Dermatology/Corticosteroid", forms: ["Cream", "Oint"], strengths: ["0.1%+0.5%"] },
  { id: 334, name: "Betnovate C", genericName: "Betamethasone + Clioquinol", category: "Dermatology/Corticosteroid", forms: ["Cream", "Oint"], strengths: ["0.1%+3%"] },
  { id: 335, name: "Clobetasol", genericName: "Clobetasol Propionate", category: "Dermatology/Corticosteroid", forms: ["Cream", "Oint", "Lotion"], strengths: ["0.05%"] },
  { id: 336, name: "Tenovate", genericName: "Clobetasol Propionate", category: "Dermatology/Corticosteroid", forms: ["Cream", "Oint"], strengths: ["0.05%"] },
  { id: 337, name: "Momate", genericName: "Mometasone Furoate", category: "Dermatology/Corticosteroid", forms: ["Cream", "Oint", "Lotion"], strengths: ["0.1%"] },
  { id: 338, name: "Elocon", genericName: "Mometasone Furoate", category: "Dermatology/Corticosteroid", forms: ["Cream", "Oint", "Lotion"], strengths: ["0.1%"] },
  { id: 339, name: "Fluticasone Cream", genericName: "Fluticasone Propionate", category: "Dermatology/Corticosteroid", forms: ["Cream"], strengths: ["0.05%"] },
  { id: 340, name: "Panderm", genericName: "Clobetasol + Neomycin + Miconazole + Chlorocresol", category: "Dermatology/Combination", forms: ["Cream"], strengths: ["0.05%+0.5%+2%+0.1%"] },
  { id: 341, name: "Quadriderm", genericName: "Beclomethasone + Neomycin + Clotrimazole + Chlorocresol", category: "Dermatology/Combination", forms: ["Cream"], strengths: ["0.025%+0.5%+1%+0.1%"] },
  { id: 342, name: "Candid B", genericName: "Clotrimazole + Beclomethasone", category: "Dermatology/Antifungal", forms: ["Cream", "Lotion"], strengths: ["1%+0.025%"] },
  { id: 343, name: "Ring Guard", genericName: "Miconazole + Zinc Undecylenate", category: "Dermatology/Antifungal", forms: ["Cream"], strengths: ["2%+20%"] },
  { id: 344, name: "Mupirocin", genericName: "Mupirocin", category: "Dermatology/Antibiotic", forms: ["Oint", "Cream"], strengths: ["2%"] },
  { id: 345, name: "T-Bact", genericName: "Mupirocin", category: "Dermatology/Antibiotic", forms: ["Oint", "Cream"], strengths: ["2%"] },
  { id: 346, name: "Fusidic Acid", genericName: "Fusidic Acid", category: "Dermatology/Antibiotic", forms: ["Cream", "Oint"], strengths: ["2%"] },
  { id: 347, name: "Fucidin", genericName: "Fusidic Acid", category: "Dermatology/Antibiotic", forms: ["Cream", "Oint"], strengths: ["2%"] },
  { id: 348, name: "Silver Sulfadiazine", genericName: "Silver Sulfadiazine", category: "Dermatology/Antibiotic", forms: ["Cream"], strengths: ["1%"] },
  { id: 349, name: "Silverex", genericName: "Silver Sulfadiazine", category: "Dermatology/Antibiotic", forms: ["Cream"], strengths: ["1%"] },
  { id: 350, name: "Adapalene", genericName: "Adapalene", category: "Dermatology/Anti-acne", forms: ["Gel"], strengths: ["0.1%", "0.3%"] },
  { id: 351, name: "Deriva", genericName: "Adapalene", category: "Dermatology/Anti-acne", forms: ["Gel"], strengths: ["0.1%"] },
  { id: 352, name: "Deriva CMS", genericName: "Adapalene + Clindamycin", category: "Dermatology/Anti-acne", forms: ["Gel"], strengths: ["0.1%+1%"] },
  { id: 353, name: "Benzoyl Peroxide", genericName: "Benzoyl Peroxide", category: "Dermatology/Anti-acne", forms: ["Gel", "Cream"], strengths: ["2.5%", "5%"] },
  { id: 354, name: "Brevoxyl", genericName: "Benzoyl Peroxide", category: "Dermatology/Anti-acne", forms: ["Cream"], strengths: ["4%"] },
  { id: 355, name: "Retino A", genericName: "Tretinoin", category: "Dermatology/Anti-acne", forms: ["Cream", "Gel"], strengths: ["0.025%", "0.05%", "0.1%"] },
  { id: 356, name: "Isotretinoin", genericName: "Isotretinoin", category: "Dermatology/Anti-acne", forms: ["Cap", "Gel"], strengths: ["5mg", "10mg", "20mg", "0.05%"] },
  { id: 357, name: "Tretiva", genericName: "Isotretinoin", category: "Dermatology/Anti-acne", forms: ["Cap"], strengths: ["5mg", "10mg", "20mg"] },
  { id: 358, name: "Calamine Lotion", genericName: "Calamine + Zinc Oxide", category: "Dermatology/Soothing", forms: ["Lotion"], strengths: ["8%+8%"] },
  { id: 359, name: "Lacto Calamine", genericName: "Calamine + Zinc Oxide + Glycerin", category: "Dermatology/Soothing", forms: ["Lotion"], strengths: ["Combination"] },
  { id: 360, name: "Permethrin", genericName: "Permethrin", category: "Dermatology/Antiparasitic", forms: ["Cream", "Lotion"], strengths: ["5%"] },
  { id: 361, name: "Tacrolimus", genericName: "Tacrolimus", category: "Dermatology/Immunosuppressant", forms: ["Oint"], strengths: ["0.03%", "0.1%"] },
  { id: 362, name: "Kojivit Gel", genericName: "Kojic Acid + Arbutin + Vitamin C", category: "Dermatology/Depigmenting", forms: ["Gel"], strengths: ["Combination"] },

  // ===== ENT =====
  { id: 363, name: "Otogesic", genericName: "Antipyrine + Benzocaine + Phenylephrine", category: "ENT/Ear Drop", forms: ["Drop"], strengths: ["54mg+14mg+5mg/ml"] },
  { id: 364, name: "Soliwax", genericName: "Docusate Sodium", category: "ENT/Ear Drop", forms: ["Drop"], strengths: ["5%"] },
  { id: 365, name: "Waxonil", genericName: "Paradichlorobenzene + Benzocaine + Chlorbutol + Turpentine Oil", category: "ENT/Ear Drop", forms: ["Drop"], strengths: ["Combination"] },
  { id: 366, name: "Candid Ear Drop", genericName: "Clotrimazole", category: "ENT/Ear Drop", forms: ["Drop"], strengths: ["1%"] },
  { id: 367, name: "Neosporin H", genericName: "Neomycin + Polymyxin B + Hydrocortisone", category: "ENT/Ear Drop", forms: ["Drop"], strengths: ["Combination"] },
  { id: 368, name: "Betnesol N", genericName: "Betamethasone + Neomycin", category: "ENT/Ear-Nose Drop", forms: ["Drop"], strengths: ["0.1%+0.5%"] },
  { id: 369, name: "Flomist", genericName: "Fluticasone Propionate", category: "ENT/Nasal Spray", forms: ["Spray"], strengths: ["50mcg/spray"] },
  { id: 370, name: "Mometasone Nasal", genericName: "Mometasone Furoate", category: "ENT/Nasal Spray", forms: ["Spray"], strengths: ["50mcg/spray"] },
  { id: 371, name: "Nasonex", genericName: "Mometasone Furoate", category: "ENT/Nasal Spray", forms: ["Spray"], strengths: ["50mcg/spray"] },
  { id: 372, name: "Azelastine Nasal", genericName: "Azelastine", category: "ENT/Nasal Spray", forms: ["Spray"], strengths: ["0.1%"] },

  // ===== OPHTHALMOLOGY =====
  { id: 373, name: "Moxifloxacin Eye Drop", genericName: "Moxifloxacin", category: "Ophthalmology/Antibiotic", forms: ["Drop"], strengths: ["0.5%"] },
  { id: 374, name: "Milflox", genericName: "Moxifloxacin", category: "Ophthalmology/Antibiotic", forms: ["Drop"], strengths: ["0.5%"] },
  { id: 375, name: "Vigamox", genericName: "Moxifloxacin", category: "Ophthalmology/Antibiotic", forms: ["Drop"], strengths: ["0.5%"] },
  { id: 376, name: "Tobramycin Eye", genericName: "Tobramycin", category: "Ophthalmology/Antibiotic", forms: ["Drop"], strengths: ["0.3%"] },
  { id: 377, name: "Tobrex", genericName: "Tobramycin", category: "Ophthalmology/Antibiotic", forms: ["Drop", "Oint"], strengths: ["0.3%"] },
  { id: 378, name: "Ciplox Eye Drop", genericName: "Ciprofloxacin", category: "Ophthalmology/Antibiotic", forms: ["Drop"], strengths: ["0.3%"] },
  { id: 379, name: "Oflox Eye Drop", genericName: "Ofloxacin", category: "Ophthalmology/Antibiotic", forms: ["Drop"], strengths: ["0.3%"] },
  { id: 380, name: "Gatiquin", genericName: "Gatifloxacin", category: "Ophthalmology/Antibiotic", forms: ["Drop"], strengths: ["0.3%"] },
  { id: 381, name: "Pred Forte", genericName: "Prednisolone Acetate", category: "Ophthalmology/Steroid", forms: ["Drop"], strengths: ["1%"] },
  { id: 382, name: "Dexamethasone Eye", genericName: "Dexamethasone", category: "Ophthalmology/Steroid", forms: ["Drop"], strengths: ["0.1%"] },
  { id: 383, name: "Lotepred", genericName: "Loteprednol", category: "Ophthalmology/Steroid", forms: ["Drop"], strengths: ["0.5%"] },
  { id: 384, name: "Nepafenac Eye", genericName: "Nepafenac", category: "Ophthalmology/NSAID", forms: ["Drop"], strengths: ["0.1%"] },
  { id: 385, name: "Ketorolac Eye", genericName: "Ketorolac Tromethamine", category: "Ophthalmology/NSAID", forms: ["Drop"], strengths: ["0.4%", "0.5%"] },
  { id: 386, name: "Refresh Tears", genericName: "Carboxymethylcellulose", category: "Ophthalmology/Lubricant", forms: ["Drop"], strengths: ["0.5%"] },
  { id: 387, name: "Systane", genericName: "Polyethylene Glycol + Propylene Glycol", category: "Ophthalmology/Lubricant", forms: ["Drop"], strengths: ["0.4%+0.3%"] },
  { id: 388, name: "Tears Naturale", genericName: "Hydroxypropyl Methylcellulose + Dextran", category: "Ophthalmology/Lubricant", forms: ["Drop"], strengths: ["0.3%+0.1%"] },
  { id: 389, name: "Timolol Eye", genericName: "Timolol", category: "Ophthalmology/Antiglaucoma", forms: ["Drop"], strengths: ["0.25%", "0.5%"] },
  { id: 390, name: "Dorzolamide Eye", genericName: "Dorzolamide", category: "Ophthalmology/Antiglaucoma", forms: ["Drop"], strengths: ["2%"] },
  { id: 391, name: "Latanoprost Eye", genericName: "Latanoprost", category: "Ophthalmology/Antiglaucoma", forms: ["Drop"], strengths: ["0.005%"] },
  { id: 392, name: "Brimonidine Eye", genericName: "Brimonidine", category: "Ophthalmology/Antiglaucoma", forms: ["Drop"], strengths: ["0.15%", "0.2%"] },
  { id: 393, name: "Tropicamide Eye", genericName: "Tropicamide", category: "Ophthalmology/Mydriatic", forms: ["Drop"], strengths: ["0.5%", "1%"] },
  { id: 394, name: "Homatropine Eye", genericName: "Homatropine", category: "Ophthalmology/Cycloplegic", forms: ["Drop"], strengths: ["2%"] },
  { id: 395, name: "Natamycin Eye", genericName: "Natamycin", category: "Ophthalmology/Antifungal", forms: ["Drop"], strengths: ["5%"] },

  // ===== ORTHOPEDIC / MUSCULOSKELETAL =====
  { id: 396, name: "Shelcal Plus", genericName: "Calcium + Vitamin D3 + Zinc + Magnesium + Copper + Manganese + Boron", category: "Orthopedic/Supplement", forms: ["Tab"], strengths: ["Combination"] },
  { id: 397, name: "Calcimax Forte", genericName: "Calcium Citrate + Vitamin D3 + Zinc + Magnesium", category: "Orthopedic/Supplement", forms: ["Tab"], strengths: ["Combination"] },
  { id: 398, name: "Ossopan D", genericName: "Calcium + Phosphorus + Vitamin D3", category: "Orthopedic/Supplement", forms: ["Tab"], strengths: ["830mg+360mg+200IU"] },
  { id: 399, name: "Alendronate", genericName: "Alendronate Sodium", category: "Orthopedic/Bisphosphonate", forms: ["Tab"], strengths: ["35mg", "70mg"] },
  { id: 400, name: "Osteofos", genericName: "Alendronate Sodium", category: "Orthopedic/Bisphosphonate", forms: ["Tab"], strengths: ["10mg", "35mg", "70mg"] },
  { id: 401, name: "Zoledronic Acid", genericName: "Zoledronic Acid", category: "Orthopedic/Bisphosphonate", forms: ["Inj"], strengths: ["4mg", "5mg/100ml"] },
  { id: 402, name: "Thiocolchicoside", genericName: "Thiocolchicoside", category: "Orthopedic/Muscle Relaxant", forms: ["Tab", "Cap", "Inj"], strengths: ["4mg", "8mg", "4mg/2ml"] },
  { id: 403, name: "Myospaz", genericName: "Chlorzoxazone + Paracetamol", category: "Orthopedic/Muscle Relaxant", forms: ["Tab"], strengths: ["250mg+300mg", "500mg+325mg"] },
  { id: 404, name: "Chlorzoxazone", genericName: "Chlorzoxazone", category: "Orthopedic/Muscle Relaxant", forms: ["Tab"], strengths: ["250mg", "500mg"] },
  { id: 405, name: "Tizanidine", genericName: "Tizanidine", category: "Orthopedic/Muscle Relaxant", forms: ["Tab", "Cap"], strengths: ["2mg", "4mg", "6mg"] },
  { id: 406, name: "Sirdalud", genericName: "Tizanidine", category: "Orthopedic/Muscle Relaxant", forms: ["Tab"], strengths: ["2mg", "4mg"] },
  { id: 407, name: "Baclofen", genericName: "Baclofen", category: "Orthopedic/Muscle Relaxant", forms: ["Tab"], strengths: ["10mg", "25mg"] },
  { id: 408, name: "Lioresal", genericName: "Baclofen", category: "Orthopedic/Muscle Relaxant", forms: ["Tab"], strengths: ["10mg", "25mg"] },
  { id: 409, name: "Myoril", genericName: "Thiocolchicoside", category: "Orthopedic/Muscle Relaxant", forms: ["Cap"], strengths: ["4mg", "8mg"] },
  { id: 410, name: "Volini Gel", genericName: "Diclofenac Diethylamine + Methyl Salicylate + Menthol", category: "Orthopedic/Topical Analgesic", forms: ["Gel", "Spray"], strengths: ["1.16%+10%+5%"] },
  { id: 411, name: "Moov", genericName: "Wintergreen Oil + Turpentine Oil + Eucalyptus Oil + Mint", category: "Orthopedic/Topical Analgesic", forms: ["Cream", "Spray"], strengths: ["Combination"] },
  { id: 412, name: "Colchicine", genericName: "Colchicine", category: "Orthopedic/Antigout", forms: ["Tab"], strengths: ["0.5mg"] },
  { id: 413, name: "Allopurinol", genericName: "Allopurinol", category: "Orthopedic/Antigout", forms: ["Tab"], strengths: ["100mg", "300mg"] },
  { id: 414, name: "Zyloric", genericName: "Allopurinol", category: "Orthopedic/Antigout", forms: ["Tab"], strengths: ["100mg", "300mg"] },
  { id: 415, name: "Febuxostat", genericName: "Febuxostat", category: "Orthopedic/Antigout", forms: ["Tab"], strengths: ["40mg", "80mg", "120mg"] },
  { id: 416, name: "Febuget", genericName: "Febuxostat", category: "Orthopedic/Antigout", forms: ["Tab"], strengths: ["40mg", "80mg"] },

  // ===== UROLOGICAL =====
  { id: 417, name: "Tamsulosin", genericName: "Tamsulosin", category: "Urological/BPH", forms: ["Cap", "Tab"], strengths: ["0.2mg", "0.4mg"] },
  { id: 418, name: "Urimax", genericName: "Tamsulosin", category: "Urological/BPH", forms: ["Cap"], strengths: ["0.2mg", "0.4mg"] },
  { id: 419, name: "Urimax D", genericName: "Tamsulosin + Dutasteride", category: "Urological/BPH", forms: ["Cap"], strengths: ["0.4mg+0.5mg"] },
  { id: 420, name: "Veltam", genericName: "Tamsulosin", category: "Urological/BPH", forms: ["Tab"], strengths: ["0.4mg"] },
  { id: 421, name: "Dutasteride", genericName: "Dutasteride", category: "Urological/BPH", forms: ["Cap"], strengths: ["0.5mg"] },
  { id: 422, name: "Finasteride", genericName: "Finasteride", category: "Urological/BPH", forms: ["Tab"], strengths: ["1mg", "5mg"] },
  { id: 423, name: "Finpecia", genericName: "Finasteride", category: "Urological/BPH/Hair Loss", forms: ["Tab"], strengths: ["1mg"] },
  { id: 424, name: "Alfuzosin", genericName: "Alfuzosin", category: "Urological/BPH", forms: ["Tab"], strengths: ["10mg"] },
  { id: 425, name: "Silodosin", genericName: "Silodosin", category: "Urological/BPH", forms: ["Cap"], strengths: ["4mg", "8mg"] },
  { id: 426, name: "Silodal", genericName: "Silodosin", category: "Urological/BPH", forms: ["Cap"], strengths: ["4mg", "8mg"] },
  { id: 427, name: "Oxybutynin", genericName: "Oxybutynin", category: "Urological/Overactive Bladder", forms: ["Tab"], strengths: ["2.5mg", "5mg"] },
  { id: 428, name: "Solifenacin", genericName: "Solifenacin", category: "Urological/Overactive Bladder", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 429, name: "Vesicare", genericName: "Solifenacin", category: "Urological/Overactive Bladder", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 430, name: "Mirabegron", genericName: "Mirabegron", category: "Urological/Overactive Bladder", forms: ["Tab"], strengths: ["25mg", "50mg"] },
  { id: 431, name: "Potassium Citrate", genericName: "Potassium Citrate", category: "Urological/Alkaliniser", forms: ["Tab", "Syp"], strengths: ["1080mg", "1100mg/5ml"] },
  { id: 432, name: "K-Cit", genericName: "Potassium Citrate + Magnesium Citrate", category: "Urological/Alkaliniser", forms: ["Syp"], strengths: ["Combination"] },

  // ===== DIURETICS =====
  { id: 433, name: "Lasix", genericName: "Furosemide", category: "Diuretic", forms: ["Tab", "Inj"], strengths: ["20mg", "40mg", "10mg/ml"] },
  { id: 434, name: "Fruselac", genericName: "Furosemide", category: "Diuretic", forms: ["Tab"], strengths: ["40mg"] },
  { id: 435, name: "Dytor", genericName: "Torsemide", category: "Diuretic", forms: ["Tab", "Inj"], strengths: ["10mg", "20mg", "40mg", "100mg"] },
  { id: 436, name: "Aldactone", genericName: "Spironolactone", category: "Diuretic", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 437, name: "Hydrochlorothiazide", genericName: "Hydrochlorothiazide", category: "Diuretic", forms: ["Tab"], strengths: ["12.5mg", "25mg"] },
  { id: 438, name: "Metolazone", genericName: "Metolazone", category: "Diuretic", forms: ["Tab"], strengths: ["2.5mg", "5mg"] },
  { id: 439, name: "Mannitol", genericName: "Mannitol", category: "Diuretic/Osmotic", forms: ["Inj"], strengths: ["10%", "20%"] },
  { id: 440, name: "Indapamide", genericName: "Indapamide", category: "Diuretic", forms: ["Tab"], strengths: ["1.5mg", "2.5mg"] },

  // ===== ANTIEMETICS =====
  { id: 441, name: "Vomistop", genericName: "Domperidone", category: "Antiemetic", forms: ["Tab", "Susp"], strengths: ["10mg", "5mg/5ml"] },
  { id: 442, name: "Ondem", genericName: "Ondansetron", category: "Antiemetic", forms: ["Tab", "Inj", "Syp"], strengths: ["4mg", "8mg", "2mg/ml"] },
  { id: 443, name: "Zofer", genericName: "Ondansetron", category: "Antiemetic", forms: ["Tab", "Inj"], strengths: ["4mg", "8mg"] },
  { id: 444, name: "Promethazine", genericName: "Promethazine", category: "Antiemetic/Antihistamine", forms: ["Tab", "Inj", "Syp"], strengths: ["10mg", "25mg", "25mg/ml", "5mg/5ml"] },
  { id: 445, name: "Stemetil", genericName: "Prochlorperazine", category: "Antiemetic", forms: ["Tab", "Inj"], strengths: ["5mg", "12.5mg/ml"] },
  { id: 446, name: "Aprepitant", genericName: "Aprepitant", category: "Antiemetic", forms: ["Cap"], strengths: ["40mg", "80mg", "125mg"] },
  { id: 447, name: "Granisetron", genericName: "Granisetron", category: "Antiemetic", forms: ["Tab", "Inj"], strengths: ["1mg", "2mg", "1mg/ml"] },

  // ===== ANTIVIRALS =====
  { id: 448, name: "Acyclovir", genericName: "Acyclovir", category: "Antiviral", forms: ["Tab", "Cream", "Inj"], strengths: ["200mg", "400mg", "800mg", "5%", "250mg vial"] },
  { id: 449, name: "Zovirax", genericName: "Acyclovir", category: "Antiviral", forms: ["Tab", "Cream"], strengths: ["200mg", "400mg", "800mg", "5%"] },
  { id: 450, name: "Valacyclovir", genericName: "Valacyclovir", category: "Antiviral", forms: ["Tab"], strengths: ["500mg", "1000mg"] },
  { id: 451, name: "Valcivir", genericName: "Valacyclovir", category: "Antiviral", forms: ["Tab"], strengths: ["500mg", "1000mg"] },
  { id: 452, name: "Oseltamivir", genericName: "Oseltamivir", category: "Antiviral", forms: ["Cap", "Susp"], strengths: ["30mg", "45mg", "75mg", "12mg/ml"] },
  { id: 453, name: "Tamiflu", genericName: "Oseltamivir", category: "Antiviral", forms: ["Cap"], strengths: ["75mg"] },
  { id: 454, name: "Famciclovir", genericName: "Famciclovir", category: "Antiviral", forms: ["Tab"], strengths: ["250mg", "500mg"] },

  // ===== ANTHELMINTICS (DEWORMING) =====
  { id: 455, name: "Albendazole", genericName: "Albendazole", category: "Anthelmintic", forms: ["Tab", "Syp"], strengths: ["200mg", "400mg", "200mg/5ml"] },
  { id: 456, name: "Zentel", genericName: "Albendazole", category: "Anthelmintic", forms: ["Tab", "Syp"], strengths: ["400mg", "200mg/5ml"] },
  { id: 457, name: "Mebendazole", genericName: "Mebendazole", category: "Anthelmintic", forms: ["Tab", "Syp"], strengths: ["100mg", "100mg/5ml"] },
  { id: 458, name: "Ivermectin", genericName: "Ivermectin", category: "Anthelmintic/Antiparasitic", forms: ["Tab"], strengths: ["3mg", "6mg", "12mg"] },

  // ===== ANTIMALARIALS =====
  { id: 459, name: "Chloroquine", genericName: "Chloroquine Phosphate", category: "Antimalarial", forms: ["Tab", "Syp"], strengths: ["250mg", "500mg", "50mg/5ml"] },
  { id: 460, name: "Lariago", genericName: "Chloroquine Phosphate", category: "Antimalarial", forms: ["Tab", "Syp"], strengths: ["250mg", "500mg"] },
  { id: 461, name: "Hydroxychloroquine", genericName: "Hydroxychloroquine Sulfate", category: "Antimalarial/Immunomodulator", forms: ["Tab"], strengths: ["200mg", "300mg", "400mg"] },
  { id: 462, name: "HCQS", genericName: "Hydroxychloroquine Sulfate", category: "Antimalarial/Immunomodulator", forms: ["Tab"], strengths: ["200mg", "300mg", "400mg"] },
  { id: 463, name: "Artesunate", genericName: "Artesunate", category: "Antimalarial", forms: ["Tab", "Inj"], strengths: ["50mg", "60mg vial"] },

  // ===== HORMONES & CONTRACEPTIVES =====
  { id: 464, name: "Progesterone", genericName: "Progesterone (Micronized)", category: "Hormone", forms: ["Cap", "Inj", "Gel"], strengths: ["100mg", "200mg", "300mg", "8%"] },
  { id: 465, name: "Susten", genericName: "Progesterone", category: "Hormone", forms: ["Cap", "Inj"], strengths: ["100mg", "200mg", "300mg"] },
  { id: 466, name: "Mala N", genericName: "Levonorgestrel + Ethinyl Estradiol", category: "Contraceptive", forms: ["Tab"], strengths: ["0.15mg+0.03mg"] },
  { id: 467, name: "Novelon", genericName: "Desogestrel + Ethinyl Estradiol", category: "Contraceptive", forms: ["Tab"], strengths: ["0.15mg+0.03mg"] },
  { id: 468, name: "Femilon", genericName: "Desogestrel + Ethinyl Estradiol", category: "Contraceptive", forms: ["Tab"], strengths: ["0.15mg+0.02mg"] },
  { id: 469, name: "Unwanted 72", genericName: "Levonorgestrel", category: "Emergency Contraceptive", forms: ["Tab"], strengths: ["1.5mg"] },
  { id: 470, name: "iPill", genericName: "Levonorgestrel", category: "Emergency Contraceptive", forms: ["Tab"], strengths: ["1.5mg"] },
  { id: 471, name: "Norethisterone", genericName: "Norethisterone", category: "Hormone", forms: ["Tab"], strengths: ["5mg"] },
  { id: 472, name: "Primolut N", genericName: "Norethisterone", category: "Hormone", forms: ["Tab"], strengths: ["5mg"] },
  { id: 473, name: "Duphaston", genericName: "Dydrogesterone", category: "Hormone", forms: ["Tab"], strengths: ["10mg"] },
  { id: 474, name: "Deviry", genericName: "Medroxyprogesterone", category: "Hormone", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg"] },

  // ===== ERECTILE DYSFUNCTION =====
  { id: 475, name: "Manforce", genericName: "Sildenafil", category: "Erectile Dysfunction", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 476, name: "Viagra", genericName: "Sildenafil", category: "Erectile Dysfunction", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 477, name: "Tadalafil", genericName: "Tadalafil", category: "Erectile Dysfunction", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg", "20mg"] },
  { id: 478, name: "Megalis", genericName: "Tadalafil", category: "Erectile Dysfunction", forms: ["Tab"], strengths: ["10mg", "20mg"] },

  // ===== MIGRAINE =====
  { id: 479, name: "Suminat", genericName: "Sumatriptan", category: "Migraine", forms: ["Tab", "Spray"], strengths: ["25mg", "50mg", "100mg", "20mg/spray"] },
  { id: 480, name: "Rizatriptan", genericName: "Rizatriptan", category: "Migraine", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 481, name: "Flunarizine", genericName: "Flunarizine", category: "Migraine Prophylaxis", forms: ["Cap", "Tab"], strengths: ["5mg", "10mg"] },
  { id: 482, name: "Sibelium", genericName: "Flunarizine", category: "Migraine Prophylaxis", forms: ["Cap"], strengths: ["5mg", "10mg"] },
  { id: 483, name: "Propranolol", genericName: "Propranolol", category: "Migraine Prophylaxis/Beta Blocker", forms: ["Tab"], strengths: ["10mg", "20mg", "40mg", "80mg"] },
  { id: 484, name: "Ciplar", genericName: "Propranolol", category: "Migraine Prophylaxis/Beta Blocker", forms: ["Tab"], strengths: ["10mg", "20mg", "40mg"] },

  // ===== IMMUNOSUPPRESSANTS =====
  { id: 485, name: "Azathioprine", genericName: "Azathioprine", category: "Immunosuppressant", forms: ["Tab"], strengths: ["25mg", "50mg"] },
  { id: 486, name: "Imuran", genericName: "Azathioprine", category: "Immunosuppressant", forms: ["Tab"], strengths: ["50mg"] },
  { id: 487, name: "Methotrexate", genericName: "Methotrexate", category: "Immunosuppressant/DMARD", forms: ["Tab", "Inj"], strengths: ["2.5mg", "5mg", "7.5mg", "10mg", "15mg", "25mg/ml"] },
  { id: 488, name: "Folitrax", genericName: "Methotrexate", category: "Immunosuppressant/DMARD", forms: ["Tab"], strengths: ["2.5mg", "5mg", "7.5mg", "10mg", "15mg"] },
  { id: 489, name: "Mycophenolate", genericName: "Mycophenolate Mofetil", category: "Immunosuppressant", forms: ["Tab", "Cap"], strengths: ["250mg", "500mg"] },
  { id: 490, name: "Cyclosporine", genericName: "Cyclosporine", category: "Immunosuppressant", forms: ["Cap", "Solution"], strengths: ["25mg", "50mg", "100mg", "100mg/ml"] },
  { id: 491, name: "Tacrolimus Oral", genericName: "Tacrolimus", category: "Immunosuppressant", forms: ["Cap"], strengths: ["0.5mg", "1mg", "5mg"] },

  // ===== MISCELLANEOUS / SPECIALTY =====
  { id: 492, name: "Dapsone", genericName: "Dapsone", category: "Antileprosy/Dermatology", forms: ["Tab"], strengths: ["50mg", "100mg"] },
  { id: 493, name: "Mesalamine", genericName: "Mesalamine (5-ASA)", category: "GI/Anti-inflammatory (IBD)", forms: ["Tab", "Susp"], strengths: ["400mg", "800mg", "1200mg"] },
  { id: 494, name: "Asacol", genericName: "Mesalamine", category: "GI/Anti-inflammatory (IBD)", forms: ["Tab"], strengths: ["400mg", "800mg"] },
  { id: 495, name: "Sulfasalazine", genericName: "Sulfasalazine", category: "GI/DMARD", forms: ["Tab"], strengths: ["500mg"] },
  { id: 496, name: "Saaz", genericName: "Sulfasalazine", category: "GI/DMARD", forms: ["Tab"], strengths: ["500mg"] },
  { id: 497, name: "Leflunomide", genericName: "Leflunomide", category: "Immunosuppressant/DMARD", forms: ["Tab"], strengths: ["10mg", "20mg"] },
  { id: 498, name: "Arava", genericName: "Leflunomide", category: "Immunosuppressant/DMARD", forms: ["Tab"], strengths: ["10mg", "20mg"] },
  { id: 499, name: "Doxophylline", genericName: "Doxophylline", category: "Respiratory/Bronchodilator", forms: ["Tab", "Syp"], strengths: ["400mg", "100mg/5ml"] },
  { id: 500, name: "Acebrophylline", genericName: "Acebrophylline", category: "Respiratory/Mucolytic", forms: ["Cap", "Syp"], strengths: ["100mg", "50mg/5ml"] },
  { id: 501, name: "Spasmo Proxyvon", genericName: "Dicyclomine + Paracetamol", category: "Antispasmodic/Analgesic", forms: ["Cap"], strengths: ["20mg+325mg"] },
  { id: 502, name: "Cyclopam", genericName: "Dicyclomine", category: "Antispasmodic", forms: ["Tab", "Inj"], strengths: ["10mg", "20mg", "10mg/ml"] },
  { id: 503, name: "Hyoscine Butylbromide", genericName: "Hyoscine Butylbromide", category: "Antispasmodic", forms: ["Tab", "Inj"], strengths: ["10mg", "20mg/ml"] },
  { id: 504, name: "Buscopan", genericName: "Hyoscine Butylbromide", category: "Antispasmodic", forms: ["Tab", "Inj"], strengths: ["10mg", "20mg/ml"] },
  { id: 505, name: "Nifedipine", genericName: "Nifedipine", category: "Antihypertensive/Calcium Channel Blocker", forms: ["Tab", "Cap"], strengths: ["5mg", "10mg", "20mg", "30mg"] },
  { id: 506, name: "Depin", genericName: "Nifedipine", category: "Antihypertensive/Calcium Channel Blocker", forms: ["Tab"], strengths: ["10mg", "20mg"] },
  { id: 507, name: "Sacubitril/Valsartan", genericName: "Sacubitril + Valsartan", category: "Cardiac/Heart Failure", forms: ["Tab"], strengths: ["24mg+26mg", "49mg+51mg", "97mg+103mg"] },
  { id: 508, name: "Entresto", genericName: "Sacubitril + Valsartan", category: "Cardiac/Heart Failure", forms: ["Tab"], strengths: ["24mg+26mg", "49mg+51mg", "97mg+103mg"] },
  { id: 509, name: "Spironolactone", genericName: "Spironolactone", category: "Cardiac/Diuretic", forms: ["Tab"], strengths: ["25mg", "50mg", "100mg"] },
  { id: 510, name: "Eplerenone", genericName: "Eplerenone", category: "Cardiac/Diuretic", forms: ["Tab"], strengths: ["25mg", "50mg"] },
  { id: 511, name: "Bisoprolol", genericName: "Bisoprolol", category: "Antihypertensive/Beta Blocker", forms: ["Tab"], strengths: ["1.25mg", "2.5mg", "5mg", "10mg"] },
  { id: 512, name: "Concor", genericName: "Bisoprolol", category: "Antihypertensive/Beta Blocker", forms: ["Tab"], strengths: ["2.5mg", "5mg", "10mg"] },
  { id: 513, name: "Verapamil", genericName: "Verapamil", category: "Antihypertensive/Calcium Channel Blocker", forms: ["Tab", "Inj"], strengths: ["40mg", "80mg", "120mg", "240mg"] },
  { id: 514, name: "Calaptin", genericName: "Verapamil", category: "Antihypertensive/Calcium Channel Blocker", forms: ["Tab"], strengths: ["40mg", "80mg", "120mg"] },
  { id: 515, name: "Ticagrelor", genericName: "Ticagrelor", category: "Antiplatelet", forms: ["Tab"], strengths: ["60mg", "90mg"] },
  { id: 516, name: "Brilinta", genericName: "Ticagrelor", category: "Antiplatelet", forms: ["Tab"], strengths: ["60mg", "90mg"] },
  { id: 517, name: "Prasugrel", genericName: "Prasugrel", category: "Antiplatelet", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 518, name: "Effient", genericName: "Prasugrel", category: "Antiplatelet", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 519, name: "Cilostazol", genericName: "Cilostazol", category: "Antiplatelet/Vasodilator", forms: ["Tab"], strengths: ["50mg", "100mg"] },
  { id: 520, name: "Pentoxifylline", genericName: "Pentoxifylline", category: "Peripheral Vasodilator", forms: ["Tab"], strengths: ["400mg"] },
  { id: 521, name: "Trental", genericName: "Pentoxifylline", category: "Peripheral Vasodilator", forms: ["Tab"], strengths: ["400mg"] },
  { id: 522, name: "Piracetam", genericName: "Piracetam", category: "Nootropic", forms: ["Tab", "Cap", "Syp"], strengths: ["400mg", "800mg", "500mg/5ml"] },
  { id: 523, name: "Nootropil", genericName: "Piracetam", category: "Nootropic", forms: ["Tab"], strengths: ["800mg", "1200mg"] },
  { id: 524, name: "Citicoline", genericName: "Citicoline", category: "Nootropic", forms: ["Tab", "Inj"], strengths: ["500mg", "1000mg", "250mg/ml"] },
  { id: 525, name: "Donepezil", genericName: "Donepezil", category: "Anti-Alzheimers", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 526, name: "Aricept", genericName: "Donepezil", category: "Anti-Alzheimers", forms: ["Tab"], strengths: ["5mg", "10mg"] },
  { id: 527, name: "Memantine", genericName: "Memantine", category: "Anti-Alzheimers", forms: ["Tab"], strengths: ["5mg", "10mg", "20mg"] },
  { id: 528, name: "Sitagliptin M", genericName: "Sitagliptin + Metformin", category: "Antidiabetic", forms: ["Tab"], strengths: ["50mg+500mg", "50mg+1000mg"] },
  { id: 529, name: "Ondansetron", genericName: "Ondansetron", category: "Antiemetic", forms: ["Tab", "Inj", "Syp"], strengths: ["4mg", "8mg", "2mg/ml"] },
  { id: 530, name: "Tranexamic Acid", genericName: "Tranexamic Acid", category: "Antifibrinolytic", forms: ["Tab", "Inj"], strengths: ["250mg", "500mg", "100mg/ml"] },
  { id: 531, name: "Pause MF", genericName: "Tranexamic Acid + Mefenamic Acid", category: "Antifibrinolytic/Analgesic", forms: ["Tab"], strengths: ["500mg+250mg"] },
  { id: 532, name: "Ethamsylate", genericName: "Ethamsylate", category: "Antihemorrhagic", forms: ["Tab", "Inj"], strengths: ["250mg", "500mg", "125mg/ml"] },
  { id: 533, name: "Adrenaline", genericName: "Epinephrine", category: "Emergency/Vasopressor", forms: ["Inj"], strengths: ["1mg/ml"] },
  { id: 534, name: "Atropine", genericName: "Atropine Sulfate", category: "Anticholinergic", forms: ["Inj", "Drop"], strengths: ["0.6mg/ml", "1%"] },
  { id: 535, name: "Dopamine", genericName: "Dopamine", category: "Emergency/Vasopressor", forms: ["Inj"], strengths: ["40mg/ml", "200mg/5ml"] },
  { id: 536, name: "Dobutamine", genericName: "Dobutamine", category: "Emergency/Inotrope", forms: ["Inj"], strengths: ["250mg/20ml"] },
  { id: 537, name: "Noradrenaline", genericName: "Norepinephrine", category: "Emergency/Vasopressor", forms: ["Inj"], strengths: ["1mg/ml", "2mg/ml"] },
  { id: 538, name: "Deriphyllin Retard", genericName: "Etophylline + Theophylline SR", category: "Respiratory/Bronchodilator", forms: ["Tab"], strengths: ["231mg+69mg"] },
  { id: 539, name: "Acotiamide", genericName: "Acotiamide", category: "GI/Prokinetic", forms: ["Tab"], strengths: ["100mg"] },
  { id: 540, name: "Itopride", genericName: "Itopride", category: "GI/Prokinetic", forms: ["Tab"], strengths: ["50mg", "150mg"] },
  { id: 541, name: "Ganaton", genericName: "Itopride", category: "GI/Prokinetic", forms: ["Tab"], strengths: ["50mg"] },
  { id: 542, name: "Levosulpiride", genericName: "Levosulpiride", category: "GI/Prokinetic", forms: ["Tab"], strengths: ["25mg", "75mg"] },
  { id: 543, name: "Deanxit", genericName: "Flupentixol + Melitracen", category: "Psychiatric/Antidepressant", forms: ["Tab"], strengths: ["0.5mg+10mg"] },
  { id: 544, name: "Minoxidil", genericName: "Minoxidil", category: "Dermatology/Hair Growth", forms: ["Solution", "Gel"], strengths: ["2%", "5%", "10%"] },
  { id: 545, name: "Tugain", genericName: "Minoxidil", category: "Dermatology/Hair Growth", forms: ["Solution", "Gel"], strengths: ["2%", "5%", "10%"] },
  { id: 546, name: "Amlodipine AT", genericName: "Amlodipine + Atenolol", category: "Antihypertensive", forms: ["Tab"], strengths: ["5mg+25mg", "5mg+50mg"] },
  { id: 547, name: "Telmisartan CT", genericName: "Telmisartan + Chlorthalidone", category: "Antihypertensive", forms: ["Tab"], strengths: ["40mg+12.5mg", "80mg+12.5mg"] },
  { id: 548, name: "Saroglitazar", genericName: "Saroglitazar", category: "Antidiabetic/Lipid-Lowering", forms: ["Tab"], strengths: ["4mg"] },
  { id: 549, name: "Lipaglyn", genericName: "Saroglitazar", category: "Antidiabetic/Lipid-Lowering", forms: ["Tab"], strengths: ["4mg"] },
  { id: 550, name: "Ezetimibe", genericName: "Ezetimibe", category: "Lipid-Lowering", forms: ["Tab"], strengths: ["10mg"] },
  { id: 551, name: "Ezedoc", genericName: "Ezetimibe", category: "Lipid-Lowering", forms: ["Tab"], strengths: ["10mg"] },
  { id: 552, name: "Cefoperazone + Sulbactam", genericName: "Cefoperazone + Sulbactam", category: "Antibiotic", forms: ["Inj"], strengths: ["1g+0.5g", "2g+1g"] },
  { id: 553, name: "Magnex", genericName: "Cefoperazone + Sulbactam", category: "Antibiotic", forms: ["Inj"], strengths: ["1.5g", "3g"] },
  { id: 554, name: "Vancomycin", genericName: "Vancomycin", category: "Antibiotic", forms: ["Inj"], strengths: ["500mg", "1g"] },
  { id: 555, name: "Colistin", genericName: "Colistimethate Sodium", category: "Antibiotic", forms: ["Inj"], strengths: ["1MIU", "2MIU"] },
  { id: 556, name: "Tigecycline", genericName: "Tigecycline", category: "Antibiotic", forms: ["Inj"], strengths: ["50mg"] },
  { id: 557, name: "Ceftazidime", genericName: "Ceftazidime", category: "Antibiotic", forms: ["Inj"], strengths: ["250mg", "500mg", "1g"] },
  { id: 558, name: "Fortum", genericName: "Ceftazidime", category: "Antibiotic", forms: ["Inj"], strengths: ["250mg", "500mg", "1g"] },
  { id: 559, name: "Imipenem + Cilastatin", genericName: "Imipenem + Cilastatin", category: "Antibiotic", forms: ["Inj"], strengths: ["250mg+250mg", "500mg+500mg"] },
  { id: 560, name: "Ertapenem", genericName: "Ertapenem", category: "Antibiotic", forms: ["Inj"], strengths: ["1g"] }
];
